// app/estudos/concilios/constantinopla-2/_data/legado.ts

export interface ConquistaDoutrinaria {
  id: string;
  titulo: string;
  descricao: string;
  permanencia: string;
}

export interface Legado {
  impactoTeologico: {
    titulo: string;
    triunfoNeocalcedoniano: string;
    ciriloInterpreteDeCalcedonia: string;
    baseParaMonotelismo: string;
    influenciaNaTeologiaPosterior: string;
  };
  impactoEclesial: {
    titulo: string;
    cicatrizesNoOcidente: string;
    rupturaComNorteDaItalia: string;
    criseNaAfrica: string;
    fracassoComMiafisitas: string;
    rejeicaoPelaIgrejaDoOriente: string;
    balancoDaComunhao: string;
  };
  impactoPolitico: {
    titulo: string;
    apogeuDaSinfonia: string;
    limitesDoCesaropapismo: string;
    reacaoOcidental: string;
    precedentesParaCrisesFuturas: string;
    legadoParaRelacaoIgrejaEstado: string;
  };
  principaisConquistas: ConquistaDoutrinaria[];
  resumoGeral: string;
}

export const legado: Legado = {
  impactoTeologico: {
    titulo: "Impacto Teológico: O Triunfo da Síntese Neocalcedoniana e suas Ramificações",
    triunfoNeocalcedoniano:
      "A contribuição teológica mais duradoura do Segundo Concílio de Constantinopla foi a consolidação definitiva da síntese neocalcedoniana como a interpretação normativa da cristologia de Calcedônia (451) no Oriente cristão. Antes de 553, a fórmula calcedonense 'em duas naturezas' (en dyo physesin) era objeto de leituras divergentes e frequentemente incompatíveis: os teólogos de tradição antioquena (Teodoro de Mopsuéstia, Teodoreto, Ibas) a interpretavam como afirmação da distinção real e operacional entre as duas naturezas de Cristo, com ênfase na integridade da humanidade assumida; os teólogos de tradição alexandrina (Cirilo, Dióscoro, Severo de Antioquia) a interpretavam como concessão relutante à dualidade, subordinada à unidade hipostática expressa pela fórmula 'uma natureza encarnada do Verbo de Deus' (mia physis tou Theou Logou sesarkōmenē). O concílio de 553 resolveu essa ambiguidade hermenêutica ao declarar que a leitura ciriliana era a única legítima: Calcedônia é ortodoxa, mas deve ser lida com as lentes dos Doze Capítulos de Cirilo de Alexandria. A fórmula resultante — 'uma hipóstase em duas naturezas' (mia hypostasis en dyo physesin) — tornou-se a expressão clássica da ortodoxia cristológica bizantina e foi sistematizada por Leôncio de Bizâncio (teoria da enhypostasia), Máximo o Confessor (dyothelismo e dyoenergismo) e João de Damasco (De Fide Orthodoxa III.3–7), permanecendo como a posição dogmática oficial da Igreja Ortodoxa e da Igreja Católica até os dias atuais. O triunfo do neocalcedonianismo significou, na prática, a marginalização irreversível da tradição exegética e cristológica antioquena no Império Bizantino: a escola de Antioquia, que já estava em declínio desde o século V, recebeu em 553 o golpe definitivo do qual nunca se recuperou.",
    ciriloInterpreteDeCalcedonia:
      "A elevação de Cirilo de Alexandria (c. 376–444) ao status de intérprete autêntico e normativo de Calcedônia é talvez a operação hermenêutica mais consequente de todo o concílio. Antes de 553, Cirilo era venerado como santo e doutor da Igreja tanto no Oriente quanto no Ocidente, mas seus Doze Capítulos (Dōdeka Kephalaia, 430) eram objeto de desconforto entre os teólogos de tradição antioquena e entre muitos ocidentais, que os consideravam excessivamente 'monofisitas' em sua linguagem (particularmente o Capítulo XII sobre o teopasquismo e o Capítulo IV sobre a indivisibilidade das expressões evangélicas). O concílio de 553 transformou esse desconforto em ortodoxia obrigatória: os Doze Capítulos foram declarados norma hermenêutica suprema para a leitura de Calcedônia, e qualquer interpretação da Definição de 451 que contradissesse os anátemas cirilianos foi formalmente anatematizada como nestoriana. Na prática, isso significou que a cristologia de Calcedônia foi cirilizada: a linguagem de 'duas naturezas' foi preservada, mas seu conteúdo foi reinterpretado em termos da união hipostática (henōsis kath' hypostasin), da comunicação de idiomas irrestrita (communicatio idiomatum) e da fórmula teopasquista ('Um da Trindade padeceu na carne'). A cirilização de Calcedônia teve consequências imensas para a teologia posterior: ela determinou a forma como os concílios subsequentes (Constantinopla III, 680–681; Niceia II, 787) abordariam as controvérsias cristológicas, e estabeleceu Cirilo como o 'selo dos Padres' (sphragis tōn paterōn) na tradição ortodoxa — uma posição que ele mantém até hoje na liturgia e na teologia bizantinas.",
    baseParaMonotelismo:
      "Paradoxalmente, o triunfo do neocalcedonianismo em 553 plantou as sementes da controvérsia monotelita que dividiria a Igreja no século VII. A insistência do concílio na unidade de sujeito em Cristo (mia hypostasis) e na fórmula teopasquista ('Um da Trindade padeceu na carne') levou alguns teólogos bizantinos a concluir que, se o sujeito de todas as operações de Cristo é o único Logos encarnado, então Cristo deve possuir também uma única vontade (thelēma) e uma única operação (energeia). Essa inferência, embora não fosse logicamente necessária (o concílio de 553 não tratou explicitamente da questão das vontades), tornou-se a base do monotelismo promovido pelo imperador Heráclio (610–641) e pelo patriarca Sérgio I de Constantinopla (610–638) como fórmula de compromisso com os miáfisitas. O Écthesis de Heráclio (638) e o Typos de Constante II (648) invocaram explicitamente a autoridade de Constantinopla II para justificar a doutrina de uma única vontade em Cristo, argumentando que a multiplicidade de vontades implicaria a multiplicidade de sujeitos, o que o concílio de 553 havia condenado. A controvérsia monotelita só foi resolvida pelo Terceiro Concílio de Constantinopla (680–681), que dogmatizou o dyothelismo (duas vontades em Cristo, divina e humana) e declarou que a unidade de hipóstase afirmada em 553 não implica a unidade de vontade, pois a vontade é propriedade da natureza (physis), não da hipóstase (hypostasis). O Terceiro Concílio de Constantinopla reafirmou a autoridade de 553, mas corrigiu a inferência monotelita que alguns teólogos haviam extraído de suas formulações.",
    influenciaNaTeologiaPosterior:
      "A influência teológica de Constantinopla II estende-se muito além da controvérsia monotelita e permeia toda a teologia dogmática posterior, tanto oriental quanto ocidental. No Oriente, a síntese neocalcedoniana de 553 tornou-se o fundamento da cristologia de Máximo o Confessor (c. 580–662), que desenvolveu a doutrina da comunicação de idiomas em termos de perichōrēsis (interpenetração mútua das naturezas) e da theōsis (deificação da natureza humana pela união com o Logos). João de Damasco (c. 675–749) sistematizou a cristologia de 553 no livro III de De Fide Orthodoxa, que se tornou o manual padrão de teologia dogmática no mundo bizantino e eslavo. No Ocidente, a recepção de 553 foi mais lenta e ambivalente, mas suas formulações influenciaram a cristologia de Tomás de Aquino (Summa Theologiae III, qq. 1–26), que aceitou a enhypostasia e a comunicação de idiomas em sua forma neocalcedoniana, e a teologia do Concílio de Florença (1439), que tentou harmonizar as tradições cristológicas latina e grega com base na síntese de 553. Na teologia contemporânea, os anátemas de 553 continuam a ser invocados nos debates sobre a cristologia kenótica (a questão de se o Logos 'esvaziou-se' de seus atributos divinos na encarnação) e sobre a compatibilidade entre a impassibilidade divina e o sofrimento de Cristo na cruz.",
  },

  impactoEclesial: {
    titulo: "Impacto Eclesial: Cicatrizes na Comunhão e o Fracasso da Reconciliação",
    cicatrizesNoOcidente:
      "O impacto eclesial mais imediato e duradouro do concílio de 553 no Ocidente foi a criação de uma fratura profunda na comunhão entre Roma e as Igrejas do norte da Itália, da Ilíria, da Gália meridional e do norte da África — uma fratura que levou mais de 150 anos para ser plenamente cicatrizada e que deixou marcas permanentes na eclesiologia ocidental. A capitulação de Vigílio (554) e a aceitação das decisões do concílio por seu sucessor Pelágio I (556–561) foram interpretadas por amplos setores do episcopado ocidental como uma traição à fé de Calcedônia e ao primado romano, gerando um cisma que não foi meramente teológico, mas também identitário e político. Os tricapitulinos ocidentais não se viam como cismáticos, mas como defensores da verdadeira fé calcedonense contra a corrupção oriental imposta por um imperador cesaropapista. Essa autopercepção de resistência legítima contra a tirania teológica tornou-se parte integrante da identidade eclesial do norte da Itália e contribuiu para a crescente consciência de que o Ocidente possuía uma tradição teológica própria (fundada em Agostinho e Leão Magno) que não podia ser subordinada às formulações gregas sem perda de integridade.",
    rupturaComNorteDaItalia:
      "A ruptura mais grave e duradoura ocorreu no norte da Itália, onde o Patriarcado de Aquileia (com sede em Grado após a invasão lombarda de 568) e a Arquidiocese de Milão romperam formalmente a comunhão com Roma e Constantinopla. O patriarca Paulino de Aquileia (557–569) convocou um sínodo provincial que anatematizou as decisões de Constantinopla II e declarou que a Sé de Roma havia perdido sua autoridade ao capitular perante Justiniano. O cisma aquileiense foi agravado pela invasão lombarda (568), que dividiu a Itália entre territórios bizantinos (Exarcado de Ravena) e lombardos, e permitiu que os tricapitulinos do interior (Aquileia-Old, sob proteção lombarda) resistissem à pressão bizantina por mais de um século. A Arquidiocese de Milão, que havia sido o centro da resistência tricapitulina sob o arcebispo Auxano (551–568), retornou à comunhão romana c. 581, mas o patriarcado de Aquileia-Old permaneceu cismático até c. 698, quando o Concílio de Pavia, durante o pontificado de Sérgio I, finalmente restaurou a unidade. O cisma de Aquileia é o mais longo da história da cristandade ocidental antes do Grande Cisma de 1054 e demonstrou que a autoridade papal, longe de ser universalmente aceita no Ocidente do século VI, dependia criticamente do consenso episcopal regional e da legitimidade percebida de suas decisões.",
    criseNaAfrica:
      "A Igreja do norte da África (províncias da África Proconsular, Bizacena e Numídia), que havia sido recentemente reconquistada por Justiniano aos vândalos arianos (533–534), foi particularmente afetada pela controvérsia dos Três Capítulos. Os bispos africanos, herdeiros da tradição teológica de Agostinho e Cipriano, possuíam uma forte consciência de autonomia eclesial e resistiram vigorosamente à imposição imperial de decisões que consideravam contrárias à fé de Calcedônia. O bispo de Cartago, Primásio, e o bispo de Hadrumeto, Facundo (autor do Pro defensione trium capitulorum), lideraram a resistência africana e foram perseguidos, exilados e depostos pela administração bizantina. A crise tricapitulina na África enfraqueceu significativamente a Igreja norte-africana, que já estava fragilizada pela perseguição vândala (429–534) e pela persistência do donatismo residual. Quando a conquista árabe islâmica atingiu o norte da África no final do século VII (647–709), a Igreja da região estava tão debilitada pelas divisões internas que não conseguiu oferecer resistência organizada e desapareceu quase completamente no espaço de dois séculos — um dos episódios mais trágicos da história do cristianismo.",
    fracassoComMiafisitas:
      "O fracasso mais significativo do concílio de 553 foi sua incapacidade de alcançar o objetivo político primário de Justiniano: a reconciliação com os miáfisitas (coptas do Egito e jacobitas sírios). A estratégia imperial era logicamente coerente: se os miáfisitas rejeitavam Calcedônia porque a consideravam nestoriana, a condenação dos Três Capítulos (os escritos mais claramente nestorianos da tradição calcedonense) deveria demonstrar que a Igreja imperial era genuinamente antinestoriana e que Calcedônia, corretamente interpretada, era compatível com a tradição ciriliana. Na prática, a estratégia fracassou completamente. Os miáfisitas, liderados por Teodósio de Alexandria (m. 566) e Jacó Baradeu (c. 500–578), rejeitaram a condenação dos Três Capítulos como insuficiente e insincera: seu problema não era com Teodoro de Mopsuéstia (cuja condenação aceitavam com prazer), mas com a própria linguagem de 'duas naturezas' de Calcedônia, que Constantinopla II reafirmou explicitamente no anátema 5. Para os miáfisitas, a fórmula 'em duas naturezas' era intrinsecamente nestoriana, independentemente de quantos anátemas contra Teodoro fossem acrescentados, e a única forma de reconciliação seria a rejeição formal de Calcedônia — algo que Justiniano não estava disposto a fazer. O resultado foi a consolidação definitiva das Igrejas miáfisitas (Copta Ortodoxa, Siríaca Ortodoxa, Armênia Apostólica, Etíope Ortodoxa) como comunhões separadas da Igreja imperial, uma divisão que persiste até os dias atuais, mais de 1.470 anos depois.",
    rejeicaoPelaIgrejaDoOriente:
      "A Igreja do Oriente (persa), herdeira da tradição teológica de Teodoro de Mopsuéstia e da escola exegética de Antioquia, rejeitou inteiramente o concílio de 553 e a condenação de seu maior doutor. A condenação póstuma de Teodoro (anátema 11) foi interpretada pela Igreja do Oriente como uma agressão direta à sua identidade teológica e litúrgica, e o concílio de 553 tornou-se o ponto de ruptura definitivo entre a cristandade siríaca oriental e o Império Bizantino. A Igreja do Oriente (hoje representada pela Igreja Assíria do Oriente e pela Antiga Igreja do Oriente) mantém a veneração de Teodoro de Mopsuéstia como 'o Intérprete' (mpaššqānā) por excelência e rejeita a autoridade de Constantinopla II até os dias atuais. As tentativas de reconciliação entre Roma e a Igreja Assíria no século XX (Declaração Cristológica Comum de 1994 entre João Paulo II e Mar Dinkha IV) contornaram a questão de Teodoro e focaram na convergência cristológica substancial, mas a condenação de 553 permanece como um obstáculo ecumênico não resolvido.",
    balancoDaComunhao:
      "O balanço eclesial do concílio de 553 é, portanto, amplamente negativo em termos de unidade cristã. O concílio não reconciliou os miáfisitas (seu objetivo primário), alienou amplos setores do episcopado ocidental (precipitando o Cisma Tricapitulino de mais de 150 anos), e aprofundou a ruptura com a Igreja do Oriente (persa). A única comunhão que o concílio fortaleceu foi a do núcleo bizantino (Constantinopla, Alexandria calcedonense, Antioquia calcedonense, Jerusalém), que aceitou a síntese neocalcedoniana como expressão definitiva da ortodoxia. A ironia histórica é que o concílio convocado por Justiniano para unificar a cristandade sob a égide imperial produziu o efeito oposto: fragmentou a comunhão em três blocos mutuamente hostis (calcedonianos neocalcedonianos, miáfisitas e tricapitulinos/nestorianos) e criou divisões que nenhum concílio posterior conseguiu superar plenamente. O legado eclesial de 553 é, assim, um alerta permanente sobre os limites da engenharia teológica imposta por decreto imperial e sobre a complexidade irreduzível da comunhão cristã.",
  },

  impactoPolitico: {
    titulo: "Impacto Político: O Apogeu e os Limites da Sinfonia Bizantina",
    apogeuDaSinfonia:
      "O Segundo Concílio de Constantinopla representa o apogeu do modelo de sinfonia (symphonia) entre Igreja e Estado no Império Bizantino, tal como concebido e praticado por Justiniano I. A Novella 6 (535) de Justiniano formulou o ideal da sinfonia com clareza clássica: 'Os maiores dons de Deus aos homens são o sacerdócio (hierōsynē) e o império (basileia); aquele serve às coisas divinas, este governa e cuida das coisas humanas; ambos, procedendo da mesma fonte, adornam a vida humana.' Na prática de 553, contudo, a sinfonia justinianéia era assimétrica: o imperador não era um parceiro igual do sacerdócio, mas seu supervisor e árbitro final. Justiniano convocou o concílio, determinou sua agenda, preparou seus documentos, coagiu o papa, e promulgou a Sentença Sinodal como lei imperial no dia seguinte à oitava sessão. O concílio de 553 é, assim, a expressão mais completa do cesaropapismo justinianeu: o imperador como theologos (teólogo), nomothetēs (legislador) e episkopos tōn ektos (bispo dos assuntos externos), exercendo uma tutela efetiva sobre a doutrina e a disciplina da Igreja. O modelo funcionou enquanto Justiniano viveu e manteve o controle do aparato imperial, mas seus limites tornaram-se evidentes imediatamente após sua morte (565), quando seus sucessores (Justino II, Tibério II, Maurício) não possuíam nem a competência teológica nem a autoridade pessoal para manter a mesma pressão sobre a Igreja.",
    limitesDoCesaropapismo:
      "Os limites do cesaropapismo justinianeu foram expostos com clareza pelo próprio fracasso do concílio de 553 em alcançar seus objetivos políticos. Justiniano gastou mais de uma década de esforço diplomático, teológico e coercitivo para condenar os Três Capítulos e reconciliar os miáfisitas, mas o resultado foi o oposto do pretendido: os miáfisitas permaneceram separados, o Ocidente entrou em cisma, e a Igreja do Oriente rejeitou o concílio inteiramente. O fracasso demonstrou que a coerção imperial podia produzir conformidade superficial no curto prazo (a maioria dos bispos orientais subscreveu a Sentença Sinodal), mas não podia gerar consenso teológico genuíno nem comunhão eclesial duradoura. A lição foi aprendida — parcialmente — pelos imperadores subsequentes: Heráclio (610–641) tentou uma abordagem mais sutil com o monotelismo (Écthesis, 638), mas também fracassou; Constante II (641–668) tentou impor o silêncio doutrinário (Typos, 648), com resultados igualmente desastrosos. A história das controvérsias cristológicas dos séculos VI e VII é, em grande medida, a história dos limites do poder imperial em matéria de fé: o imperador podia convocar concílios, depor patriarcas e exilar papas, mas não podia forçar a consciência teológica dos fiéis nem garantir a recepção eclesial de suas decisões.",
    reacaoOcidental:
      "A reação ocidental ao cesaropapismo de 553 foi um dos fatores mais importantes na formação da identidade eclesial do Ocidente medieval. A humilhação de Vigílio e a imposição da condenação dos Três Capítulos por decreto imperial geraram uma desconfiança duradoura em relação à interferência do poder secular em questões de fé, que se expressou na reafirmação da doutrina gelasiana das 'duas espadas' (Gelasius I, Epistula 8, 494) e na crescente insistência do papado em sua independência em relação ao Império Bizantino. O Papa Gregório Magno (590–604), que aceitou as decisões de 553 mas rejeitou o título 'bispo universal' do patriarca de Constantinopla, personificou essa nova postura de independência papal: Roma reconhecia a autoridade dogmática dos concílios ecumênicos, mas recusava a tutela teológica do imperador. A reação ocidental contra o cesaropapismo de 553 contribuiu significativamente para o distanciamento gradual entre Roma e Constantinopla que culminaria no Grande Cisma de 1054 e na formação de duas eclesiologias distintas: a oriental (sinodal-imperial, com o imperador como guardião da ortodoxia) e a ocidental (papal, com o bispo de Roma como árbitro supremo da fé).",
    precedentesParaCrisesFuturas:
      "O concílio de 553 estabeleceu precedentes que seriam invocados repetidamente nas crises eclesiais dos séculos seguintes. A condenação póstuma de Teodoro de Mopsuéstia foi citada como precedente para a condenação póstuma do Papa Honório I pelo Terceiro Concílio de Constantinopla (681) e para a condenação de Fócio pelo Quarto Concílio de Constantinopla (869–870). A distinção persona/sedes, formulada na sétima sessão para justificar a excomunhão de Vigílio sem romper com a Sé de Roma, foi invocada durante o cisma de Fócio (867) e nas negociações de Florença (1439). O modelo de concílio ecumênico sem participação papal (159 bispos orientais, 6 ocidentais) foi citado pelos conciliaristas medievais (Marsílio de Pádua, Concílio de Constança 1414–1418) como prova de que a Igreja pode funcionar sem o papa. A promulgação da Sentença Sinodal como lei imperial (nomos) foi invocada pelos imperadores iconoclastas (Leão III, 726; Constantino V, 754) para justificar a imposição de suas reformas litúrgicas por decreto. Em cada um desses casos, o precedente de 553 foi instrumentalizado para fins que Justiniano provavelmente não teria previsto nem aprovado.",
    legadoParaRelacaoIgrejaEstado:
      "O legado de Constantinopla II para a relação entre Igreja e Estado é ambivalente e contestado. Na tradição ortodoxa, a sinfonia justinianéia é vista como um ideal teopolítico legítimo, embora sua aplicação concreta em 553 seja reconhecida como excessiva; o modelo da symphonia influenciou a relação entre a Igreja Ortodoxa e os Estados nacionais (Rússia, Grécia, Romênia, Sérvia) até o século XX e permanece como referência na teologia política ortodoxa contemporânea. Na tradição católica, o cesaropapismo de 553 é rejeitado como uma distorção da relação correta entre o poder espiritual e o temporal, e a crise de Vigílio é citada como prova da necessidade da libertas Ecclesiae (liberdade da Igreja) em relação ao poder secular — um princípio que seria dogmatizado pelo Concílio Vaticano II (Dignitatis Humanae, 1965). Na historiografia secular, o concílio de 553 é frequentemente apresentado como o exemplo paradigmático de instrumentalização política da religião, embora estudiosos recentes (Dagron 1996, Cameron 1993) tenham matizado essa interpretação ao demonstrar que a relação entre Justiniano e a Igreja era mais complexa e negociada do que o modelo cesaropapista simplista sugere.",
  },

  principaisConquistas: [
    {
      id: "sintese-cirilo-calcedonia",
      titulo: "Síntese definitiva entre Cirilo de Alexandria e Calcedônia",
      descricao:
        "O concílio realizou a operação hermenêutica mais consequente da história da cristologia: demonstrar que a fórmula calcedonense 'em duas naturezas' (en dyo physesin) e a fórmula ciriliana 'uma natureza encarnada do Verbo de Deus' (mia physis tou Theou Logou sesarkōmenē) não são contraditórias, mas complementares, desde que se distinga physis como essência abstrata (Calcedônia) de physis como hipóstase concreta (Cirilo). A fórmula resultante — 'uma hipóstase em duas naturezas' — tornou-se a expressão normativa da ortodoxia cristológica.",
      permanencia:
        "Permanece como a posição dogmática oficial da Igreja Católica e da Igreja Ortodoxa. Foi confirmada pelo Terceiro Concílio de Constantinopla (681), pelo Quarto Concílio de Constantinopla (870), pelo Concílio de Florença (1439) e pelo Catecismo da Igreja Católica (nn. 464–469).",
    },
    {
      id: "dogmatizacao-teopasquismo",
      titulo: "Dogmatização da fórmula teopasquista",
      descricao:
        "O concílio consagrou dogmaticamente a fórmula 'Um da Santa Trindade padeceu na carne' (heis tēs hagias Triados peponten sarki / Unus de sancta Trinitate passus est in carne), rejeitando tanto o teopasquismo radical (a natureza divina sofreu em si mesma) quanto o nestorianismo impassibilista (apenas o homem Jesus sofreu). A fórmula preserva simultaneamente a realidade da paixão (o sujeito é o próprio Logos) e a impassibilidade da natureza divina (o modo da paixão é carnal, não divino).",
      permanencia:
        "A fórmula permanece na liturgia bizantina no Trisagion ampliado ('Santo Deus, Santo Forte, Santo Imortal, que foste crucificado por nós, tem piedade de nós') e é aceita como dogma pela Igreja Católica e pela Igreja Ortodoxa. Sua relevância teológica foi reafirmada nos debates contemporâneos sobre a teologia da cruz (theologia crucis) e o sofrimento de Deus (Jürgen Moltmann, O Deus Crucificado, 1972).",
    },
    {
      id: "teoria-enhypostasia",
      titulo: "Consolidação da teoria da enhypostasia",
      descricao:
        "Embora o termo técnico enhypostasia (enympostaton) não apareça explicitamente nos anátemas de 553, a lógica do concílio pressupõe e consolida a teoria desenvolvida por Leôncio de Bizâncio (c. 485–543): a natureza humana de Cristo é anhypostatos (sem hipóstase própria e independente) e enhypostatos (subsistente na hipóstase do Logos divino). Essa teoria resolve a dificuldade mais persistente da cristologia calcedonense: como afirmar a completude da humanidade de Cristo (corpo e alma racionais) sem concluir que há duas hipóstases em Cristo.",
      permanencia:
        "A enhypostasia tornou-se a explicação padrão da união hipostática na teologia escolástica (Tomás de Aquino, Summa Theologiae III, q. 2, a. 2–3) e na teologia ortodoxa (João de Damasco, De Fide Orthodoxa III.9). Permanece como o modelo cristológico dominante nas tradições católica e ortodoxa.",
    },
    {
      id: "condenacao-origenismo",
      titulo: "Condenação abrangente do sistema origenista-evagriano",
      descricao:
        "Os quinze anátemas anti-origenistas associados ao concílio (seja por ratificação direta ou por recepção subsequente) constituem a condenação mais abrangente de um sistema teológico especulativo na história dos concílios ecumênicos. Os anátemas delimitam as fronteiras da especulação cristã legítima ao rejeitar a pré-existência das almas, a queda primordial dos intelectos, a apocatástase universal, a natureza esférica dos corpos ressuscitados, a temporalidade do reino de Cristo e a absorção panteísta das criaturas na divindade.",
      permanencia:
        "A condenação da apocatástase como doutrina (não como esperança orante) permanece vinculante na Igreja Católica e na Igreja Ortodoxa. Os anátemas foram confirmados pelo Sínodo Quinissexto (692) e pelo Segundo Concílio de Niceia (787). O debate contemporâneo sobre a esperança de salvação universal (von Balthasar, Hart) opera dentro dos limites estabelecidos por esses anátemas.",
    },
    {
      id: "theotokos-propria",
      titulo: "Reafirmação da Theotokos em sentido próprio e verdadeiro",
      descricao:
        "O concílio reafirmou e radicalizou o título Theotokos (Mãe de Deus) ao insistir em que Maria é Theotokos 'própria e verdadeiramente' (kyriōs kai kat' alētheian), rejeitando a concessão nominal 'por relação' (kata schesin) de Teodoro de Mopsuéstia. A maternidade divina de Maria foi declarada o teste litúrgico e devocional da união hipostática: quem nega Theotokos em sentido próprio nega, de facto, que o Logos se fez verdadeiramente carne.",
      permanencia:
        "O título Theotokos permanece como dogma fundamental da mariologia católica e ortodoxa. Foi reafirmado pelo Concílio de Éfeso (431), por Calcedônia (451), por Constantinopla II (553) e pelo Concílio Vaticano II (Lumen Gentium, nn. 52–69, 1964). A qualificação 'própria e verdadeira' de 553 continua a ser a norma hermenêutica para a interpretação do título.",
    },
    {
      id: "adoracao-unica",
      titulo: "Definição da adoração única de Cristo (uma proskynēsis)",
      descricao:
        "Os anátemas 7 e 8 do concílio definiram que a adoração (proskynēsis / adoratio) devida a Cristo é única e indivisível, dirigida à pessoa do Verbo encarnado com sua carne, e não dupla (uma para a natureza divina e outra para a natureza humana). A adoração única é o corolário litúrgico da união hipostática: se há um só sujeito em Cristo, há uma só adoração.",
      permanencia:
        "A doutrina da adoração única permanece como norma litúrgica e dogmática na Igreja Católica e na Igreja Ortodoxa. Sua aplicação prática é visível na liturgia eucarística, onde a adoração é dirigida a Cristo como um todo (theanthropos, Deus-homem), sem distinção entre suas naturezas.",
    },
    {
      id: "distincao-pessoa-sede",
      titulo: "Formulação da distinção canônica persona/sedes",
      descricao:
        "A sétima sessão do concílio formulou a distinção canônica entre a persona do papa (julgável e condenável por heresia ou contumácia) e a sedes Romana (intangível e permanentemente ortodoxa por promessa divina). Essa distinção permitiu ao concílio excomungar Vigílio pessoalmente sem romper a comunhão com a Sé de Pedro, uma manobra de sofisticação jurídica sem precedente.",
      permanencia:
        "A distinção persona/sedes tornou-se um instrumento canônico fundamental na eclesiologia medieval e moderna. Foi invocada durante o cisma de Fócio (867), o Grande Cisma do Ocidente (1378–1417), o Concílio de Constança (1414–1418) e os debates do Vaticano I (1870) sobre a infalibilidade papal. Permanece como um dos conceitos mais debatidos da eclesiologia contemporânea.",
    },
    {
      id: "quatro-concilios-como-unidade",
      titulo: "Reafirmação dos quatro concílios como corpo dogmático indivisível",
      descricao:
        "A Sentença Final do concílio declarou que 'a fé dos quatro concílios ecumênicos — Niceia, Constantinopla, Éfeso e Calcedônia — é uma e indivisível', estabelecendo o princípio de que os concílios ecumênicos formam um corpus dogmático orgânico e coerente, no qual cada concílio interpreta e complementa os anteriores sem contradizê-los. Constantinopla II se apresentou como o 'quinto pilar' dessa estrutura, não como sua substituição.",
      permanencia:
        "O princípio da continuidade e coerência dos concílios ecumênicos permanece como axioma fundamental da teologia dogmática tanto católica quanto ortodoxa. A ideia de que os concílios formam uma 'sinfonia dogmática' (symphōnia dogmatikē) foi desenvolvida por Máximo o Confessor e por João de Damasco e permanece como o modelo normativo de desenvolvimento doutrinário.",
    },
  ],

  resumoGeral:
    "O Segundo Concílio de Constantinopla (553 d.C.) ocupa uma posição singular e paradoxal na história do cristianismo. Teologicamente, foi um triunfo: a síntese neocalcedoniana que produziu — harmonizando a linguagem de 'duas naturezas' de Calcedônia com a tradição ciriliana da união hipostática, da comunicação de idiomas e do teopasquismo — é uma das realizações intelectuais mais sofisticadas da teologia cristã e permanece como a posição dogmática oficial das maiores tradições cristãs até os dias atuais. A dogmatização da fórmula 'Um da Trindade padeceu na carne', a consolidação da enhypostasia e a reafirmação da Theotokos em sentido próprio são contribuições teológicas de primeira grandeza que transcendem amplamente o contexto político de sua produção. Eclesialmente, contudo, o concílio foi um fracasso de proporções históricas: não alcançou seu objetivo primário de reconciliação com os miáfisitas, precipitou o Cisma Tricapitulino que dividiu o Ocidente por mais de 150 anos, aprofundou a ruptura com a Igreja do Oriente (persa) e deixou cicatrizes na comunhão entre Roma e Constantinopla que contribuíram para o Grande Cisma de 1054. Politicamente, o concílio representou o apogeu do cesaropapismo justinianeu e, simultaneamente, a demonstração mais eloquente de seus limites: o imperador podia convocar concílios, coagir papas e promulgar definições de fé como leis imperiais, mas não podia forçar a consciência teológica dos fiéis nem garantir a recepção eclesial de suas decisões. O legado de Constantinopla II é, assim, uma lição permanente sobre a complexidade da relação entre ortodoxia dogmática, comunhão eclesial e poder político — uma lição que a cristandade continua a aprender e a reaprender, 1.470 anos após a oitava sessão na Hagia Sophia.",
};