export const tresCapitulos = {
  introducao:
    'A expressão "Três Capítulos" (latim: Tria Capitula; grego: Τρία Κεφάλαια) não se refere a três documentos ou três sessões de um concílio, mas a três "pessoas e seus escritos" (capitula no sentido de "tópicos" ou "itens de acusação") que Justiniano I condenou por édito imperial em 543/544 e que o V Concílio Ecumênico anatematizou em 553. Os Três Capítulos são: (1) a pessoa e os escritos de Teodoro de Mopsuéstia; (2) os escritos de Teodoreto de Ciro contra Cirilo de Alexandria e o I Concílio de Éfeso; (3) a Carta de Ibas de Edessa a Mari, o Persa. A controvérsia em torno desses três itens é o cerne absoluto do Concílio de Constantinopla II e a razão de sua convocação. Sem compreender os Três Capítulos, é impossível compreender o V Concílio.',

  oDilema:
    'O dilema era aparentemente insolúvel: Calcedônia (451) havia reabilitado Teodoreto e Ibas (ambos depostos no Latrocínio de Éfeso em 449) e nunca condenara Teodoro de Mopsuéstia, que morrera em comunhão com a Igreja em 428. Condenar os Três Capítulos parecia, portanto, atacar a autoridade de Calcedônia — o que o Ocidente não aceitava. Por outro lado, não os condenar perpetuava a divisão com os miafisitas, que viam nos Três Capítulos a prova de que Calcedônia era secretamente nestoriana. Justiniano tentou resolver o dilema distinguindo entre "pessoas" (que Calcedônia havia absolvido) e "escritos" (que podiam ser condenados independentemente), mas a distinção era artificial e não convenceu o Ocidente.',

  // =============================================
  // PRIMEIRO CAPÍTULO: TEODORO DE MOPSUÉSTIA
  // =============================================
  capitulo1: {
    quemFoi:
      'Teodoro de Mopsuéstia (~350–428) foi bispo de Mopsuéstia, uma pequena cidade da Cilícia (sul da atual Turquia), de 392 até sua morte em 428. Formado na Escola de Antioquia sob a orientação de Diodoro de Tarso, Teodoro foi o mais prolífico e sistemático exegeta da tradição antioquena. Ele escreveu comentários sobre quase todos os livros da Bíblia, tratados dogmáticos, catequeses batismais e obras polêmicas. Durante sua vida, foi respeitado como um dos maiores teólogos do Oriente; Teodoreto de Ciro o chamava de "o Doutor da Igreja universal". Sua cristologia, no entanto, era radicalmente diofisita: insistia na distinção real entre a natureza divina e a natureza humana em Cristo, usando a metáfora da "inhabitação" (ἐνοίκησις) do Logos no homem Jesus como um templo. Ele se recusava a chamar Maria de Theotokos (Mãe de Deus), preferindo Christotokos (Mãe de Cristo), e distinguia dois "filhos" — o Filho de Deus por natureza e o filho de Davi por adoção — unidos em uma única "prosopon" (aparência/pessoa) exterior.',
    obras:
      'Comentário sobre os Salmos (parcialmente conservado em latim); Comentário sobre os Profetas Menores (conservado); Comentário sobre o Evangelho de João (fragmentos); Catequese Batismal (conservada em siríaco); Sobre a Encarnação (De Incarnatione, fragmentos); Contra os Magos (perdida); Sobre a Criação (fragmentos). A maioria de suas obras foi destruída após a condenação de 553, sobrevivendo apenas em traduções siríacas e latinas e em citações nos Acta do concílio.',
    doutrina:
      'A cristologia de Teodoro partia da distinção absoluta entre as duas naturezas (divina e humana) em Cristo. Ele ensinava que o Logos divino "habitava" no homem Jesus como em um templo (inhabitação), e que a união entre as duas naturezas era uma união de "boa vontade" (εὐδοκία) e de "prosopon" (aparência exterior), não uma união hipostática real. Ele distinguia dois sujeitos de atribuição: ao Logos atribuía os milagres e a eternidade; ao homem Jesus atribuía o sofrimento, o crescimento e a morte. Esta distinção levava a formulações que soavam nestorianas: "Um é aquele que é adorado, outro é aquele que adora"; "O homem assumido é o templo do Logos". Embora Teodoro tenha morrido antes da controvérsia nestoriana (428), sua teologia foi a fonte intelectual de Nestório, que havia sido seu aluno em Antioquia.',
    porQueCondenado:
      'Justiniano condenou Teodoro porque seus escritos continham, em sua avaliação, a raiz intelectual do nestorianismo. Os trechos lidos no concílio (Sessões III–IV) demonstravam que Teodoro: (1) distinguia dois "filhos" em Cristo; (2) negava a união hipostática em favor de uma união de prosopon; (3) recusava o título Theotokos para Maria; (4) atribuía o sofrimento e a morte apenas ao homem Jesus, não ao Logos; (5) ensinava que a união das duas naturezas era progressiva e baseada na "boa vontade" divina. Para Justiniano e os padres do concílio, essas posições eram incompatíveis com a fé de Cirilo de Alexandria e com a Definição de Calcedônia, interpretada à luz de Cirilo.',
    problemaDaCondenacaoPostuma:
      'A condenação de Teodoro era juridicamente sem precedentes por três razões: (1) Ele morreu em 428 em plena comunhão com a Igreja, antes da controvérsia nestoriana; (2) Nenhum concílio anterior o havia condenado — nem Éfeso (431), nem Calcedônia (451); (3) Teodoreto de Ciro, um dos padres de Calcedônia, o chamava de "Doutor universal". Condenar Teodoro 125 anos após sua morte significava julgar retroativamente um homem que a Igreja havia considerado ortodoxo durante toda a sua vida. Os defensores dos Três Capítulos (Facundo de Hermiane) argumentavam que condenar os mortos era violar o princípio canônico de que "a Igreja não julga os que morreram em comunhão" e que isso abria um precedente perigoso: qualquer autor morto poderia ser reavaliado e condenado retroativamente.',
    trechosCondenados:
      'Entre os trechos lidos na Sessão III do concílio: (1) Do tratado Sobre a Encarnação: "O Logos habitou naquele que nasceu de Maria como em um templo, e o uniu a si por uma conjunção de boa vontade"; (2) Do Comentário sobre João: "Um é o Filho de Deus por natureza, outro é o filho de Davi por adoção; a união é de prosopon, não de hipóstase"; (3) Da Catequese Batismal: "Não devemos dizer que Deus nasceu de Maria, pois a divindade não pode nascer; devemos dizer que o homem nascido de Maria foi unido a Deus"; (4) Do Comentário sobre os Salmos: "Cristo é o ícone de Deus invisível não por natureza, mas por graça, como Adão era o ícone de Deus antes da queda".',
    defesa:
      'Facundo de Hermiane, no Pro Defensione Trium Capitulorum (Livros I–IV), argumentou que: (1) Teodoro morreu em comunhão e não pode ser julgado postumamente; (2) Seus escritos foram citados fora de contexto pelos compiladores de Justiniano; (3) Muitos Padres ortodoxos (incluindo João Crisóstomo e Basílio) usaram linguagem semelhante sem serem condenados; (4) A condenação de Teodoro implicaria a condenação de toda a tradição antioquena, incluindo Diodoro de Tarso e o próprio Crisóstomo. Os bispos africanos e ilírios compartilhavam essa posição.',
  },

  // =============================================
  // SEGUNDO CAPÍTULO: TEODORETO DE CIRO
  // =============================================
  capitulo2: {
    quemFoi:
      'Teodoreto de Ciro (~393–~457/466) foi bispo de Ciro, uma pequena cidade da província de Eufratense (norte da Síria), de 423 até sua morte. Formado na tradição antioquena e discípulo espiritual de Teodoro de Mopsuéstia, Teodoreto foi um dos mais brilhantes teólogos e historiadores do século V. Ele é autor de uma História Eclesiástica (continuação de Eusébio), uma História dos Monges da Síria (Historia Religiosa), o Eranistes (um diálogo cristológico em três livros), e uma Refutação dos 12 Anátemas de Cirilo de Alexandria. Teodoreto foi um dos líderes da oposição a Cirilo durante a controvérsia nestoriana (428–433). Ele foi deposto no "Latrocínio" de Éfeso (449) por Dioscuro de Alexandria, mas foi reabilitado no Concílio de Calcedônia (451) após anatematizar Nestório publicamente. Sua reabilitação em Calcedônia é o ponto central da controvérsia: como pode um concílio posterior condenar os escritos de alguém que Calcedônia absolveu?',
    obras:
      'Historia Ecclesiastica (5 livros, 325–428); Historia Religiosa (Vidas de monges sírios); Eranistes (diálogo cristológico em 3 livros, ~447); Refutação dos 12 Anátemas de Cirilo (~431); Comentário sobre as Epístolas Paulinas (conservado); Comentário sobre o Cântico dos Cânticos; Haereticarum Fabularum Compendium (compêndio de heresias). Diferentemente de Teodoro de Mopsuéstia, a maioria das obras de Teodoreto sobreviveu, pois sua condenação foi limitada aos escritos contra Cirilo.',
    doutrina:
      'A cristologia de Teodoreto era diofisita moderada, mais próxima de Calcedônia do que a de Teodoro de Mopsuéstia. Ele insistia na realidade das duas naturezas após a união e rejeitava a fórmula cirilina "uma natureza encarnada" como eutiquiana. No Eranistes, ele argumentava que as propriedades de cada natureza permaneciam intactas após a união: a divindade não sofria, a humanidade não era onipotente. Sua oposição a Cirilo era focada nos 12 Anátemas de 430, que ele considerava apolinaristas (especialmente o 4º anátema, que atribuía tanto os atos divinos quanto os humanos ao mesmo sujeito). No entanto, após 433, Teodoreto aceitou a Fórmula de União de 433 e entrou em comunhão com Cirilo, embora nunca tenha retirado suas críticas aos 12 Anátemas.',
    porQueCondenado:
      'O concílio condenou especificamente os escritos de Teodoreto contra Cirilo de Alexandria e contra o I Concílio de Éfeso (431). Os trechos lidos na Sessão V incluíam: (1) Da Refutação dos 12 Anátemas: passagens onde Teodoreto acusava Cirilo de apolinarismo e de confundir as duas naturezas; (2) Do Eranistes: diálogos onde o "Ortodoxo" (Teodoreto) argumentava que a divindade do Logos não sofreu na cruz; (3) Cartas onde Teodoreto defendia Nestório e atacava a deposição de 431. A condenação era limitada a esses escritos específicos, não a toda a obra de Teodoreto — uma distinção que os defensores consideravam artificial.',
    problemaDaCondenacaoPostuma:
      'O caso de Teodoreto era ainda mais problemático que o de Teodoro de Mopsuéstia porque: (1) Teodoreto havia sido formalmente reabilitado pelo Concílio de Calcedônia (451) na Sessão VIII, após anatematizar Nestório; (2) Os padres de Calcedônia o aclamaram como "ortodoxo" e o restauraram à sua sé; (3) Condenar seus escritos contra Cirilo parecia minar a autoridade de Calcedônia, que havia julgado esses mesmos escritos e considerado seu autor ortodoxo. Facundo de Hermiane argumentava que "se Teodoreto é herege, então Calcedônia é herege por tê-lo absolvido; e se Calcedônia é ortodoxa, então Teodoreto é ortodoxo".',
    defesa:
      'Os defensores argumentavam que: (1) Teodoreto escreveu contra Cirilo antes da reconciliação de 433; após 433, ele aceitou a Fórmula de União e morreu em comunhão com a Igreja; (2) Calcedônia examinou seus escritos e o absolveu; (3) Seus escritos contra Cirilo eram parte de uma disputa legítima entre dois grandes teólogos, não uma heresia; (4) A linguagem de Teodoreto era antioquena, não nestoriana — ele distinguia as naturezas sem dividir a pessoa, o que é perfeitamente compatível com Calcedônia.',
  },

  // =============================================
  // TERCEIRO CAPÍTULO: IBAS DE EDESSA
  // =============================================
  capitulo3: {
    quemFoi:
      'Ibas de Edessa (†457) foi bispo de Edessa (atual Şanlıurfa, Turquia) de 435 a 457, com uma interrupção entre 449 e 451. Antes de ser bispo, Ibas foi presbítero e diretor da Escola de Edessa (a "Escola dos Persas"), o principal centro de teologia antioquena no Oriente. Ele era um admirador declarado de Teodoro de Mopsuéstia e traduziu várias de suas obras para o siríaco. Durante a controvérsia nestoriana, Ibas escreveu uma carta a Mari, um clérigo persa, na qual criticava Cirilo de Alexandria e elogiava Teodoro. Esta carta, escrita por volta de 433–435, tornou-se o Terceiro Capítulo e o documento mais debatido do concílio.',
    aCarta:
      'A "Carta a Mari, o Persa" foi escrita por Ibas por volta de 433–435, durante o período de tensão entre a Escola de Antioquia e Cirilo de Alexandria. Na carta, Ibas: (1) Criticava Cirilo por seus 12 Anátemas, que considerava apolinaristas; (2) Elogiava Teodoro de Mopsuéstia como "o maior doutor da Igreja"; (3) Descrevia a controvérsia nestoriana como um mal-entendido causado pela arrogância de Cirilo; (4) Afirmava que Nestório havia sido injustamente deposto; (5) Usava linguagem que distinguia claramente as duas naturezas em Cristo. A carta era um documento privado, não um tratado teológico, e foi interceptada e usada contra Ibas no Latrocínio de Éfeso (449), onde ele foi deposto. Em Calcedônia (451), a carta foi lida na Sessão X, e os legados papais declararam que Ibas era ortodoxo porque havia anatematizado Nestório e aceitado a Fórmula de União de 433.',
    doutrina:
      'A cristologia de Ibas, tal como expressa na Carta a Mari, era antioquena moderada. Ele distinguia as duas naturezas em Cristo com clareza e insistia que a união era de "prosopon" (pessoa exterior), não de "hipóstase" (substância). Ele escrevia: "O mediador entre Deus e os homens, o homem Jesus Cristo, é um com o Filho de Deus em dignidade e honra, mas não em natureza." Esta linguagem, embora compatível com a tradição antioquena, era inaceitável para os cirilianos e para os miafisitas, que viam nela uma divisão de Cristo em dois sujeitos.',
    porQueCondenada:
      'A Carta a Mari foi condenada porque: (1) Elogiava Teodoro de Mopsuéstia e sua teologia nestoriana; (2) Atacava Cirilo de Alexandria e seus 12 Anátemas; (3) Defendia Nestório e questionava a legitimidade de sua deposição em Éfeso (431); (4) Usava linguagem que distinguia dois "filhos" em Cristo; (5) Para os miafisitas, a carta era a prova definitiva de que a tradição antioquena (e, por extensão, Calcedônia) era secretamente nestoriana. Justiniano argumentava que, embora Calcedônia tivesse absolvido a pessoa de Ibas, não havia aprovado o conteúdo da carta — uma distinção que os defensores consideravam sofística.',
    problemaDaCondenacaoPostuma:
      'O caso de Ibas era o mais agudo dos três porque a Carta a Mari havia sido lida e discutida explicitamente em Calcedônia (Sessão X, 451). Os legados papais (Paschasinus e Lucêncio) e os bispos orientais haviam declarado Ibas ortodoxo e o restauraram à sua sé. Condenar a carta era, portanto, contradizer diretamente uma decisão de Calcedônia. Facundo de Hermiane argumentava: "Se a carta é herética, então Calcedônia é herética por tê-la aprovado; se Calcedônia é ortodoxa, então a carta é ortodoxa." Justiniano respondia que Calcedônia havia julgado a pessoa de Ibas (que havia anatematizado Nestório), não o conteúdo teológico da carta — uma distinção que a maioria dos historiadores modernos considera insustentável.',
    defesa:
      'Os defensores argumentavam que: (1) A carta foi escrita antes da reconciliação de 433 e não refletia a posição final de Ibas; (2) Calcedônia examinou a carta e a considerou compatível com a ortodoxia; (3) Ibas morreu em comunhão com a Igreja; (4) A carta era um documento privado, não um tratado dogmático, e não devia ser julgada com o mesmo rigor que um símbolo de fé; (5) Condenar a carta era condenar a autoridade de Calcedônia, que a havia aprovado.',
  },

  posicaoDeJustiniano:
    'Justiniano argumentava que Calcedônia não havia "aprovado" os Três Capítulos, mas apenas "tolerado" as pessoas de Teodoreto e Ibas por razões de economia eclesiástica (oikonomia). Segundo Justiniano, os padres de Calcedônia sabiam que os escritos de Teodoreto e a carta de Ibas continham erros, mas preferiram não os condenar para evitar um novo cisma. A condenação dos Três Capítulos em 553 não era, portanto, uma revogação de Calcedônia, mas uma "completude" (πλήρωμα) de Calcedônia: o que o IV Concílio havia deixado implícito, o V Concílio tornava explícito. Justiniano também argumentava que a fé não muda, mas a compreensão da fé se aprofunda — e que os Três Capítulos eram incompatíveis com a verdadeira fé de Calcedônia, interpretada à luz de Cirilo.',

  posicaoDoOcidente:
    'O Ocidente latino (papado, bispos da Gália, da Hispânia, da Dalmácia, do Ilírico e do norte da África) rejeitava a distinção de Justiniano como sofística. Para o Ocidente, Calcedônia era um todo indivisível: suas decisões sobre pessoas e sobre doutrina eram inseparáveis. Condenar os escritos que Calcedônia havia examinado e aprovado era atacar a autoridade do IV Concílio e, por extensão, a autoridade de todos os concílios ecumênicos. Facundo de Hermiane resumiu a posição ocidental: "Quem ataca os Três Capítulos ataca Calcedônia; quem ataca Calcedônia ataca a fé dos apóstolos." Além disso, o Ocidente via na condenação póstuma uma violação do princípio canônico de que a Igreja não julga os mortos e uma concessão perigosa aos miafisitas, que acabariam por exigir a condenação do próprio Tomo de Leão.',
}