import type { LiturgicalWeek, LiturgicalSeason } from '../_types';

// ============================================================
// 🎨 CORES DOS TEMPOS LITÚRGICOS (usadas no anel externo)
// ============================================================
export const SEASON_COLORS: Record<LiturgicalSeason, string> = {
  advento: '#C7B8E0',       // lilás claro
  natal: '#F5F1E4',         // creme/branco
  tempoComum: '#5BA85B',    // verde
  quaresma: '#B39BC8',      // roxo médio
  triduoPascal: '#9B2C2C',  // vermelho vinho
  pascoa: '#FDFCF7',        // branco puro
};

// ============================================================
// 🎨 CORES ESPECÍFICAS DE SOLENIDADES (paramentos)
// ============================================================
const WHITE = '#FDFCF7';   // paramento branco
const RED = '#9B2C2C';     // paramento vermelho

// ============================================================
// 🏷️ NOMES DOS TEMPOS
// ============================================================
export const SEASON_LABELS: Record<LiturgicalSeason, string> = {
  advento: 'Advento',
  natal: 'Natal',
  tempoComum: 'Tempo Comum',
  quaresma: 'Quaresma',
  triduoPascal: 'Tríduo',
  pascoa: 'Páscoa',
};

// ============================================================
// 📅 SEMANAS DO ANO LITÚRGICO
// ============================================================
export const LITURGICAL_WEEKS: LiturgicalWeek[] = [

  // ==================== ADVENTO (4) ====================
  {
    id: 'adv-1',
    label: '1ª semana',
    season: 'advento',
    color: SEASON_COLORS.advento,
    liturgicalColor: 'Roxo',
    theme: 'Vigilância e esperança',
    description: 'Primeira semana do Advento — tempo de espera vigilante pela vinda do Senhor.',
    reflection: 'O Advento nos convida a "ficar de pé, de cabeça erguida" (Lc 21,28). É tempo de conversão interior, de preparar o coração para acolher Cristo que vem — não apenas no Natal, mas em cada momento da vida e na plenitude dos tempos.',
    readings: {
      firstReading: 'Is 2,1-5 (Ano A) | Is 63,16b-17.19b (Ano B) | Jr 33,14-16 (Ano C)',
      psalm: 'Sl 121 / 79 / 24',
      secondReading: 'Rm 13,11-14 | 1Cor 1,3-9 | 1Ts 3,12–4,2',
      gospel: 'Mt 24,37-44 | Mc 13,33-37 | Lc 21,25-28.34-36',
    },
    prayer: 'Dai aos vossos fiéis, ó Deus onipotente, a firme vontade de sair ao encontro do Cristo que vem, praticando obras de justiça, para que, reunidos à sua direita, mereçamos possuir o Reino dos Céus.',
  },
  {
    id: 'adv-2',
    label: '2ª semana',
    season: 'advento',
    color: SEASON_COLORS.advento,
    liturgicalColor: 'Roxo',
    theme: 'Preparai o caminho do Senhor',
    description: 'Segunda semana do Advento — a voz de João Batista ressoa: "Preparai o caminho do Senhor".',
    reflection: 'João Batista é a figura central desta semana. Ele nos chama à conversão e a "endireitar os caminhos" para que o Senhor possa vir ao nosso encontro. É tempo de examinar a consciência e voltar-se sinceramente para Deus.',
    readings: {
      firstReading: 'Is 11,1-10 | Is 40,1-5.9-11 | Bar 5,1-9',
      psalm: 'Sl 71 / 84 / 125',
      gospel: 'Mt 3,1-12 | Mc 1,1-8 | Lc 3,1-6',
    },
    prayer: 'Deus de bondade e misericórdia, não permitais que os cuidados da vida presente impeçam os que anseiam pelo vosso Filho de irem ao seu encontro, mas ensinai-nos a apreciar as coisas do céu.',
  },
  {
    id: 'adv-3',
    label: '3ª semana',
    season: 'advento',
    color: SEASON_COLORS.advento,
    liturgicalColor: 'Rosa (Domingo Gaudete)',
    theme: 'Alegria — o Senhor está próximo',
    description: 'Terceira semana do Advento — o Domingo Gaudete traz um clima de alegria pela proximidade do Salvador.',
    reflection: '"Alegrai-vos sempre no Senhor. De novo vos digo, alegrai-vos! O Senhor está próximo" (Fl 4,4-5). É o domingo em que o padre pode usar paramento rosa, sinal da alegria que rompe a austeridade do tempo penitencial.',
    readings: {
      firstReading: 'Is 35,1-6a.10 | Is 61,1-2a.10-11 | Sf 3,14-18a',
      psalm: 'Sl 145 / Cântico: Lc 1 / Is 12',
      gospel: 'Mt 11,2-11 | Jo 1,6-8.19-28 | Lc 3,10-18',
    },
  },
  {
    id: 'adv-4',
    label: '4ª semana',
    season: 'advento',
    color: SEASON_COLORS.advento,
    liturgicalColor: 'Roxo',
    theme: 'A Virgem conceberá',
    description: 'Quarta semana do Advento — o mistério da Encarnação se aproxima. Maria é a figura central.',
    reflection: 'Nesta última semana antes do Natal, contemplamos Maria, a Virgem que acolheu o Verbo em seu ventre. Seu "sim" (fiat) é modelo de como devemos nos abrir ao mistério de Deus.',
    readings: {
      firstReading: 'Is 7,10-14 | 2Sm 7,1-5.8b-12.14a.16 | Mq 5,1-4a',
      gospel: 'Mt 1,18-24 | Lc 1,26-38 | Lc 1,39-45',
    },
    prayer: 'Derramai, ó Deus, a vossa graça em nossos corações, para que, conhecendo pela mensagem do anjo a encarnação do vosso Filho, cheguemos, por sua paixão e cruz, à glória da ressurreição.',
  },

  // ==================== NATAL (5) ====================
  {
    id: 'natal',
    label: 'Natal',
    season: 'natal',
    color: SEASON_COLORS.natal,
    liturgicalColor: 'Branco',
    theme: 'O Verbo se fez carne',
    description: 'Solenidade do Natal do Senhor — celebração do nascimento de Jesus Cristo.',
    reflection: '"E o Verbo se fez carne e habitou entre nós" (Jo 1,14). Deus se faz homem por amor à humanidade. O Natal não é apenas memória de um evento passado — é celebração do Deus-conosco que continua nascendo em nossos corações.',
    readings: {
      firstReading: 'Is 52,7-10 (Missa do Dia)',
      psalm: 'Sl 97',
      secondReading: 'Hb 1,1-6',
      gospel: 'Jo 1,1-18',
    },
    prayer: 'Ó Deus, que de modo admirável criastes o ser humano e de modo mais admirável ainda restaurastes a sua dignidade, dai-nos participar da divindade do vosso Filho, que se dignou assumir a nossa humanidade.',
  },
  {
    id: 'sagrada-familia',
    label: 'Sagrada Família',
    season: 'natal',
    color: SEASON_COLORS.natal,
    liturgicalColor: 'Branco',
    theme: 'Modelo de vida familiar',
    description: 'Festa da Sagrada Família de Jesus, Maria e José — celebrada no domingo dentro da oitava do Natal.',
    reflection: 'A Sagrada Família de Nazaré é modelo de toda família cristã: unidade no amor, obediência à vontade de Deus, trabalho, oração e simplicidade. Nela contemplamos como a santidade cresce na convivência doméstica.',
    prayer: 'Ó Deus, dai-nos imitar os exemplos da Sagrada Família, para que, praticando as virtudes domésticas e os laços do amor, cheguemos às eternas alegrias da vossa casa.',
  },
  {
    id: 'mae-de-deus',
    label: 'Mãe de Deus',
    season: 'natal',
    color: SEASON_COLORS.natal,
    liturgicalColor: 'Branco',
    theme: 'Maria, Mãe de Deus e da Igreja',
    description: 'Solenidade de Santa Maria, Mãe de Deus — celebrada em 1º de janeiro. Dia Mundial da Paz.',
    reflection: 'Título dogmático definido no Concílio de Éfeso (431): Maria é "Theotokos" — a que gerou Deus. Nela, a maternidade humana toca o mistério divino. É também o Dia Mundial da Paz, instituído por São Paulo VI.',
    readings: {
      firstReading: 'Nm 6,22-27',
      psalm: 'Sl 66',
      secondReading: 'Gl 4,4-7',
      gospel: 'Lc 2,16-21',
    },
  },
  {
    id: 'epifania',
    label: 'Epifania do Senhor',
    season: 'natal',
    color: SEASON_COLORS.natal,
    liturgicalColor: 'Branco',
    theme: 'Manifestação de Cristo às nações',
    description: 'Solenidade da Epifania do Senhor — a manifestação de Jesus aos Magos, representantes de todos os povos.',
    reflection: 'A luz que brilhou em Belém não é apenas para Israel — é para todas as nações. Os Magos representam a humanidade inteira, chamada a reconhecer Cristo. Seus dons têm significado: ouro (rei), incenso (Deus), mirra (homem mortal).',
    readings: {
      firstReading: 'Is 60,1-6',
      psalm: 'Sl 71',
      secondReading: 'Ef 3,2-3a.5-6',
      gospel: 'Mt 2,1-12',
    },
  },
  {
    id: 'batismo',
    label: 'Batismo do Senhor',
    season: 'natal',
    color: SEASON_COLORS.natal,
    liturgicalColor: 'Branco',
    theme: 'Início da vida pública de Jesus',
    description: 'Festa do Batismo do Senhor — encerra o Tempo do Natal e inicia o Tempo Comum.',
    reflection: 'No Jordão, Jesus se solidariza com os pecadores e recebe a manifestação do Pai: "Este é o meu Filho amado". Nosso batismo nos torna filhos amados no Filho, incorporados à missão do Cristo.',
    readings: {
      firstReading: 'Is 42,1-4.6-7 | Is 55,1-11 | Is 40,1-5.9-11',
      gospel: 'Mt 3,13-17 | Mc 1,7-11 | Lc 3,15-16.21-22',
    },
  },

  // ==================== TEMPO COMUM — PARTE 1 (6) ====================
  {
    id: 'tc1-1',
    label: '1ª semana',
    season: 'tempoComum',
    color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde',
    theme: 'Início do seguimento',
    description: '1ª semana do Tempo Comum — inicia-se após o Batismo do Senhor.',
    reflection: 'Terminado o Tempo do Natal, começamos a acompanhar Jesus em seu ministério público. É tempo de crescer no discipulado dia após dia, na vida ordinária.',
  },
  {
    id: 'tc1-2',
    label: '2ª semana',
    season: 'tempoComum',
    color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde',
    theme: 'Vinde e vede',
    description: '2ª semana do Tempo Comum.',
    reflection: 'Os primeiros discípulos perguntam a Jesus: "Onde moras?". Ele responde: "Vinde e vede" (Jo 1,39). É o convite que ecoa ao coração de todo cristão.',
  },
  {
    id: 'tc1-3',
    label: '3ª semana',
    season: 'tempoComum',
    color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde',
    theme: 'Convertei-vos e crede no Evangelho',
    description: '3ª semana do Tempo Comum — Domingo da Palavra de Deus (instituído pelo Papa Francisco).',
    reflection: 'Jesus inicia sua pregação com um chamado radical: conversão e fé. Neste domingo, a Igreja celebra especialmente a centralidade da Sagrada Escritura na vida cristã.',
  },
  {
    id: 'tc1-4',
    label: '4ª semana',
    season: 'tempoComum',
    color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde',
    theme: 'As Bem-aventuranças',
    description: '4ª semana do Tempo Comum.',
    reflection: 'A proclamação das Bem-aventuranças (Mt 5) apresenta o "manifesto" do Reino: felizes os pobres, os mansos, os que têm sede de justiça. É a lógica invertida de Deus.',
  },
  {
    id: 'tc1-5',
    label: '5ª semana',
    season: 'tempoComum',
    color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde',
    theme: 'Sal da terra e luz do mundo',
    description: '5ª semana do Tempo Comum.',
    reflection: '"Vós sois o sal da terra... vós sois a luz do mundo" (Mt 5,13-14). O cristão não vive para si — sua vida deve dar sabor e iluminar o mundo.',
  },
  {
    id: 'tc1-etc',
    label: '...',
    season: 'tempoComum',
    color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde',
    theme: 'Semanas variáveis',
    description: 'Semanas seguintes do Tempo Comum, que podem ser interrompidas pelo início da Quaresma dependendo do ano.',
    reflection: 'A quantidade exata de semanas do Tempo Comum antes da Quaresma varia conforme a data da Páscoa. Alguns anos há mais semanas, outros menos.',
  },

  // ==================== QUARESMA (7) ====================
  {
    id: 'cinzas',
    label: '4ª feira de Cinzas',
    season: 'quaresma',
    color: SEASON_COLORS.quaresma,
    liturgicalColor: 'Roxo',
    theme: 'Convertei-vos e crede no Evangelho',
    description: 'Quarta-feira de Cinzas — início solene da Quaresma. Dia de jejum e abstinência.',
    reflection: 'A imposição das cinzas nos lembra: "És pó e ao pó voltarás" (Gn 3,19). É o convite radical à conversão. Iniciamos 40 dias de oração, jejum e esmola em preparação à Páscoa.',
    readings: {
      firstReading: 'Jl 2,12-18',
      psalm: 'Sl 50',
      secondReading: '2Cor 5,20–6,2',
      gospel: 'Mt 6,1-6.16-18',
    },
    prayer: 'Concedei-nos, ó Deus, iniciar com este dia de jejum a caminhada quaresmal, para que a nossa penitência seja o testemunho da nossa conversão.',
  },
  {
    id: 'qua-1',
    label: '1ª semana',
    season: 'quaresma',
    color: SEASON_COLORS.quaresma,
    liturgicalColor: 'Roxo',
    theme: 'Tentação no deserto',
    description: '1ª semana da Quaresma — Jesus é tentado no deserto.',
    reflection: 'Como Jesus, somos chamados ao "deserto" quaresmal: lugar de silêncio, de combate espiritual, de encontro profundo com Deus. Suas respostas às tentações (com a Palavra) são modelo para nós.',
    readings: {
      firstReading: 'Gn 2,7-9;3,1-7 | Gn 9,8-15 | Dt 26,4-10',
      gospel: 'Mt 4,1-11 | Mc 1,12-15 | Lc 4,1-13',
    },
  },
  {
    id: 'qua-2',
    label: '2ª semana',
    season: 'quaresma',
    color: SEASON_COLORS.quaresma,
    liturgicalColor: 'Roxo',
    theme: 'Transfiguração',
    description: '2ª semana da Quaresma — a Transfiguração do Senhor no monte.',
    reflection: 'Antes da cruz, Jesus revela sua glória no Tabor. É antecipação da Páscoa: mostrando aos discípulos quem Ele verdadeiramente é, para que não desanimem diante da paixão.',
    readings: {
      firstReading: 'Gn 12,1-4a | Gn 22,1-2.9a.10-13.15-18 | Gn 15,5-12.17-18',
      gospel: 'Mt 17,1-9 | Mc 9,2-10 | Lc 9,28b-36',
    },
  },
  {
    id: 'qua-3',
    label: '3ª semana',
    season: 'quaresma',
    color: SEASON_COLORS.quaresma,
    liturgicalColor: 'Roxo',
    theme: 'A água viva',
    description: '3ª semana da Quaresma — no Ano A, o encontro com a samaritana.',
    reflection: '"Quem beber da água que eu lhe der, nunca mais terá sede" (Jo 4,14). Cristo é a água viva que sacia a sede mais profunda do coração humano. Semana ligada ao mistério do Batismo.',
    readings: {
      firstReading: 'Ex 17,3-7 (Ano A)',
      gospel: 'Jo 4,5-42 (Ano A)',
    },
  },
  {
    id: 'qua-4',
    label: '4ª semana',
    season: 'quaresma',
    color: SEASON_COLORS.quaresma,
    liturgicalColor: 'Rosa (Domingo Laetare)',
    theme: 'A luz do mundo',
    description: '4ª semana da Quaresma — Domingo Laetare, marcado por uma alegria antecipada da Páscoa.',
    reflection: 'No Ano A, a cura do cego de nascença (Jo 9). Cristo é a luz que abre nossos olhos. O Domingo Laetare traz um respiro de alegria: a Páscoa se aproxima.',
    readings: {
      firstReading: '1Sm 16,1b.6-7.10-13a (Ano A)',
      gospel: 'Jo 9,1-41 (Ano A)',
    },
  },
  {
    id: 'qua-5',
    label: '5ª semana',
    season: 'quaresma',
    color: SEASON_COLORS.quaresma,
    liturgicalColor: 'Roxo',
    theme: 'Ressurreição e vida',
    description: '5ª semana da Quaresma — no Ano A, a ressurreição de Lázaro.',
    reflection: '"Eu sou a ressurreição e a vida" (Jo 11,25). Cristo antecipa sua própria vitória sobre a morte ao ressuscitar Lázaro. É o último grande sinal antes da Paixão.',
    readings: {
      firstReading: 'Ez 37,12-14 (Ano A)',
      gospel: 'Jo 11,1-45 (Ano A)',
    },
  },
  {
    id: 'ramos',
    label: 'Domingo de Ramos',
    season: 'quaresma',
    color: RED,
    liturgicalColor: 'Vermelho',
    theme: 'Entrada messiânica e Paixão',
    description: 'Domingo de Ramos da Paixão do Senhor — encerra a Quaresma e inicia a Semana Santa.',
    reflection: 'Duas cenas contrastantes: a entrada triunfal em Jerusalém ("Hosana!") e a Paixão ("Crucifica-o!"). Mesmas multidões, sentimentos opostos. Somos convidados a acompanhar Jesus nos passos finais rumo à cruz.',
    readings: {
      firstReading: 'Is 50,4-7',
      psalm: 'Sl 21',
      secondReading: 'Fl 2,6-11',
      gospel: 'Mt 26,14–27,66 | Mc 14,1–15,47 | Lc 22,14–23,56',
    },
  },

  // ==================== TRÍDUO PASCAL (3) ====================
  {
    id: 'quinta-santa',
    label: '5ª feira Santa',
    season: 'triduoPascal',
    color: WHITE,
    liturgicalColor: 'Branco',
    theme: 'Ceia do Senhor — Eucaristia e serviço',
    description: 'Quinta-feira Santa — Missa da Ceia do Senhor. Início do Tríduo Pascal.',
    reflection: 'Três dons são instituídos nesta noite santa: a Eucaristia, o Sacerdócio ministerial e o mandamento novo do amor ("Amai-vos como eu vos amei"). O lava-pés mostra que a Eucaristia é serviço.',
    readings: {
      firstReading: 'Ex 12,1-8.11-14',
      psalm: 'Sl 115',
      secondReading: '1Cor 11,23-26',
      gospel: 'Jo 13,1-15',
    },
    prayer: 'Ó Deus, reunidos para a santa ceia em que vosso Filho, prestes a entregar-se à morte, confiou à Igreja o novo e eterno sacrifício, banquete do seu amor, dai-nos alcançar deste tão grande mistério a plenitude do amor e da vida.',
  },
  {
    id: 'sexta-santa',
    label: '6ª feira Santa',
    season: 'triduoPascal',
    color: SEASON_COLORS.triduoPascal,
    liturgicalColor: 'Vermelho',
    theme: 'Paixão e morte do Senhor',
    description: 'Sexta-feira Santa — Paixão do Senhor. Dia de jejum e abstinência.',
    reflection: 'Único dia do ano em que não se celebra a Missa. A Igreja se une à Paixão de Cristo em silêncio, adoração da Cruz e oração universal pelo mundo. "Eis o lenho da Cruz, do qual pendeu a salvação do mundo."',
    readings: {
      firstReading: 'Is 52,13–53,12',
      psalm: 'Sl 30',
      secondReading: 'Hb 4,14-16;5,7-9',
      gospel: 'Jo 18,1–19,42',
    },
  },
  {
    id: 'pascoa',
    label: 'Páscoa',
    season: 'triduoPascal',
    color: WHITE,
    liturgicalColor: 'Branco',
    theme: 'Ressurreição do Senhor',
    description: 'Domingo de Páscoa — Ressurreição do Senhor. Ápice do ano litúrgico.',
    reflection: 'Cristo venceu a morte! Este é "o dia que o Senhor fez para nós" (Sl 117,24). A Vigília Pascal, na noite de sábado, é a "mãe de todas as vigílias" — celebra em quatro grandes partes (luz, palavra, água, eucaristia) o mistério central da fé cristã.',
    readings: {
      firstReading: 'At 10,34a.37-43',
      psalm: 'Sl 117',
      secondReading: 'Cl 3,1-4 ou 1Cor 5,6b-8',
      gospel: 'Jo 20,1-9',
    },
    prayer: 'Ó Deus, que neste dia, pela vitória do vosso Filho sobre a morte, nos abristes as portas da eternidade, dai-nos, pela vossa graça preveniente, corresponder aos vossos apelos.',
  },

  // ==================== PÁSCOA (8) ====================
  {
    id: 'pas-2',
    label: '2ª semana',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Divina Misericórdia',
    description: '2ª semana da Páscoa — Domingo da Divina Misericórdia (instituído por São João Paulo II).',
    reflection: 'Tomé, que duvidou, faz a mais alta profissão de fé: "Meu Senhor e meu Deus!" (Jo 20,28). Neste domingo celebramos a misericórdia infinita de Cristo Ressuscitado, que sopra o Espírito e envia os discípulos.',
    readings: {
      firstReading: 'At 2,42-47 | At 4,32-35 | At 5,12-16',
      gospel: 'Jo 20,19-31',
    },
  },
  {
    id: 'pas-3',
    label: '3ª semana',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Discípulos de Emaús',
    description: '3ª semana da Páscoa.',
    reflection: 'Jesus se faz reconhecer "ao partir do pão" (Lc 24,35). A Eucaristia é o lugar privilegiado onde o Ressuscitado continua caminhando conosco e nos abre o coração à sua Palavra.',
  },
  {
    id: 'pas-4',
    label: '4ª semana',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Bom Pastor',
    description: '4ª semana da Páscoa — Domingo do Bom Pastor. Dia Mundial de Oração pelas Vocações.',
    reflection: '"Eu sou o Bom Pastor. O bom pastor dá a vida por suas ovelhas" (Jo 10,11). Cristo conhece cada um pelo nome. Neste domingo, rezamos por todas as vocações — sacerdotais, religiosas, matrimoniais, leigas.',
    readings: {
      gospel: 'Jo 10,1-10 | Jo 10,11-18 | Jo 10,27-30',
    },
  },
  {
    id: 'pas-5',
    label: '5ª semana',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Videira verdadeira',
    description: '5ª semana da Páscoa.',
    reflection: '"Eu sou a videira, vós os ramos" (Jo 15,5). A vida cristã não é auto-suficiência: é permanecer em Cristo, alimentar-se de sua seiva, dar fruto pela união com Ele.',
  },
  {
    id: 'pas-6',
    label: '6ª semana',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Amai-vos uns aos outros',
    description: '6ª semana da Páscoa.',
    reflection: 'Jesus deixa como mandamento maior o amor mútuo. E promete: "Não vos deixarei órfãos" — enviará o Paráclito, o Espírito Santo. Estamos nos aproximando de Pentecostes.',
  },
  {
    id: 'ascensao',
    label: 'Ascensão do Senhor',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Cristo à direita do Pai',
    description: 'Solenidade da Ascensão do Senhor.',
    reflection: 'Jesus sobe ao céu, mas não nos abandona: entronizado à direita do Pai, envia o Espírito Santo e permanece presente na Igreja. "Ide, pois, e ensinai todas as nações" — a missão nos é confiada.',
    readings: {
      firstReading: 'At 1,1-11',
      psalm: 'Sl 46',
      secondReading: 'Ef 1,17-23',
      gospel: 'Mt 28,16-20 | Mc 16,15-20 | Lc 24,46-53',
    },
  },
  {
    id: 'pas-7',
    label: '7ª semana',
    season: 'pascoa',
    color: SEASON_COLORS.pascoa,
    liturgicalColor: 'Branco',
    theme: 'Espera do Espírito',
    description: '7ª semana da Páscoa — semana que antecede Pentecostes.',
    reflection: 'Os apóstolos, reunidos com Maria no Cenáculo, aguardam o Espírito Prometido. É semana de intensa oração comunitária, preparação para o "batismo no Espírito" que a Igreja recebe em Pentecostes.',
  },
  {
    id: 'pentecostes',
    label: 'Pentecostes',
    season: 'pascoa',
    color: RED,
    liturgicalColor: 'Vermelho',
    theme: 'Vinda do Espírito Santo',
    description: 'Solenidade de Pentecostes — encerra o Tempo Pascal. Nascimento da Igreja.',
    reflection: 'O Espírito Santo desce como línguas de fogo. A Igreja nasce. Os apóstolos, antes trancados por medo, saem pelas ruas anunciando as maravilhas de Deus em todas as línguas. É a nova criação.',
    readings: {
      firstReading: 'At 2,1-11',
      psalm: 'Sl 103',
      secondReading: '1Cor 12,3b-7.12-13',
      gospel: 'Jo 20,19-23',
    },
    prayer: 'Ó Deus, que pelo mistério da festa de hoje santificais a vossa Igreja estendida por todos os povos e nações, derramai sobre a face da terra os dons do Espírito Santo.',
  },

  // ==================== TEMPO COMUM — PARTE 2 (25) ====================
  {
    id: 'trindade',
    label: 'Ss. Trindade',
    season: 'tempoComum',
    color: WHITE,
    liturgicalColor: 'Branco',
    theme: 'Mistério do Deus Uno e Trino',
    description: 'Solenidade da Santíssima Trindade — celebrada no domingo após Pentecostes.',
    reflection: 'Deus é comunhão de amor: Pai, Filho e Espírito Santo. Um só Deus em três Pessoas. Este é o mistério central da fé cristã, e a fonte de nossa vocação à comunhão.',
    readings: {
      gospel: 'Mt 28,16-20 | Jo 3,16-18 | Jo 16,12-15',
    },
  },
  {
    id: 'corpus-christi',
    label: 'Corpus Christi',
    season: 'tempoComum',
    color: WHITE,
    liturgicalColor: 'Branco',
    theme: 'O Corpo e Sangue do Senhor',
    description: 'Solenidade do Santíssimo Corpo e Sangue de Cristo.',
    reflection: 'A Eucaristia é "fonte e ápice de toda a vida cristã" (LG 11). Neste dia, a Igreja sai às ruas em procissão, adorando publicamente o Cristo presente no Sacramento. "Isto é o meu Corpo, entregue por vós."',
    readings: {
      firstReading: 'Dt 8,2-3.14b-16a | Ex 24,3-8 | Gn 14,18-20',
      gospel: 'Jo 6,51-58 | Mc 14,12-16.22-26 | Lc 9,11b-17',
    },
  },
  {
    id: 'tc2-12', label: '12ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Não temer',
    description: '12ª semana do Tempo Comum.',
    reflection: '"Não tenhais medo" (Mt 10,26). Jesus prepara os discípulos para as dificuldades do anúncio do Reino. A confiança no Pai é o segredo do apóstolo.',
  },
  {
    id: 'tc2-13', label: '13ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Seguir sem reservas',
    description: '13ª semana do Tempo Comum.',
    reflection: 'Seguir Cristo exige radicalidade: "Quem ama seu pai ou sua mãe mais do que a mim, não é digno de mim" (Mt 10,37). Não se trata de menos amor, mas de amor bem ordenado.',
  },
  {
    id: 'tc2-14', label: '14ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Jugo suave',
    description: '14ª semana do Tempo Comum.',
    reflection: '"Vinde a mim, todos os que estais cansados... meu jugo é suave e meu fardo, leve" (Mt 11,28-30). Cristo não elimina a cruz, mas dá força para carregá-la com Ele.',
  },
  {
    id: 'tc2-15', label: '15ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Semeador',
    description: '15ª semana do Tempo Comum.',
    reflection: 'A parábola do semeador (Mt 13). A Palavra é lançada com generosidade em todos os terrenos. A pergunta é: que tipo de terra sou eu?',
  },
  {
    id: 'tc2-16', label: '16ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Trigo e joio',
    description: '16ª semana do Tempo Comum.',
    reflection: 'Trigo e joio crescem juntos até a colheita. Deus é paciente com o pecador e nos ensina a discernir sem julgar precipitadamente.',
  },
  {
    id: 'tc2-17', label: '17ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Tesouro escondido',
    description: '17ª semana do Tempo Comum.',
    reflection: 'O Reino dos Céus é como um tesouro escondido, uma pérola preciosa. Quem o descobre vende tudo por ele. Que preço estou disposto a pagar pela vida em Cristo?',
  },
  {
    id: 'tc2-18', label: '18ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Multiplicação dos pães',
    description: '18ª semana do Tempo Comum.',
    reflection: 'Com cinco pães e dois peixes, Jesus alimenta milhares. Ensina que a fome do mundo se sacia quando cada um oferece o pouco que tem.',
  },
  {
    id: 'tc2-19', label: '19ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Caminhar sobre as águas',
    description: '19ª semana do Tempo Comum.',
    reflection: 'Pedro caminha sobre as águas enquanto olha para Jesus; começa a afundar quando olha para o vento. Metáfora da vida cristã: manter os olhos fixos em Cristo.',
  },
  {
    id: 'tc2-20', label: '20ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Fé da cananeia',
    description: '20ª semana do Tempo Comum.',
    reflection: 'A fé insistente da mulher cananeia (Mt 15,21-28). Ela não desiste, mesmo diante do silêncio aparente de Jesus. "Mulher, grande é a tua fé!"',
  },
  {
    id: 'tc2-21', label: '21ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Confissão de Pedro',
    description: '21ª semana do Tempo Comum.',
    reflection: '"Tu és o Cristo, o Filho do Deus vivo" (Mt 16,16). Sobre esta fé, Jesus edifica a Igreja e confia as chaves a Pedro. É o momento fundacional do primado.',
  },
  {
    id: 'tc2-22', label: '22ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Renunciar-se e seguir',
    description: '22ª semana do Tempo Comum.',
    reflection: '"Quem quiser vir após mim, negue-se a si mesmo, tome sua cruz e siga-me" (Mt 16,24). O caminho de Cristo passa pela cruz — não há atalhos.',
  },
  {
    id: 'tc2-23', label: '23ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Correção fraterna',
    description: '23ª semana do Tempo Comum.',
    reflection: 'Jesus ensina como corrigir o irmão em falta, com delicadeza e progressão. "Onde dois ou três estiverem reunidos em meu nome, aí estarei no meio deles" (Mt 18,20).',
  },
  {
    id: 'tc2-24', label: '24ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Perdão sem medida',
    description: '24ª semana do Tempo Comum.',
    reflection: '"Setenta vezes sete" — o perdão cristão não conta, é infinito, à imagem do perdão que recebemos de Deus. A parábola do servo mau ilustra a exigência da misericórdia recíproca.',
  },
  {
    id: 'tc2-25', label: '25ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Os operários da vinha',
    description: '25ª semana do Tempo Comum.',
    reflection: 'Deus paga o mesmo aos que trabalharam a jornada inteira e aos que chegaram na última hora. A lógica da graça não é justiça humana — é generosidade divina.',
  },
  {
    id: 'tc2-26', label: '26ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Sim e não',
    description: '26ª semana do Tempo Comum.',
    reflection: 'A parábola dos dois filhos: um disse "sim" e não fez; outro disse "não" e foi. Vale mais a obediência efetiva do que a promessa vazia.',
  },
  {
    id: 'tc2-27', label: '27ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Vinhateiros infiéis',
    description: '27ª semana do Tempo Comum.',
    reflection: 'A vinha do Senhor foi entregue a vinhateiros que a exploram e matam os enviados. O Filho será também morto — mas se tornará pedra angular.',
  },
  {
    id: 'tc2-28', label: '28ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Banquete do Reino',
    description: '28ª semana do Tempo Comum.',
    reflection: 'O Reino é como uma festa de casamento. Os convidados recusam; a mesa se enche com "todos que encontrardes". A salvação é oferecida a todos, mas exige vestir a veste nupcial.',
  },
  {
    id: 'tc2-29', label: '29ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'A César o que é de César',
    description: '29ª semana do Tempo Comum. Dia Mundial das Missões.',
    reflection: '"Dai a César o que é de César, e a Deus o que é de Deus" (Mt 22,21). Jesus ensina a distinção entre a ordem civil e a ordem espiritual, sem opor uma à outra.',
  },
  {
    id: 'tc2-30', label: '30ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Maior mandamento',
    description: '30ª semana do Tempo Comum.',
    reflection: 'Amarás o Senhor teu Deus com todo o coração... e o próximo como a ti mesmo (Mt 22,37-39). Toda a Lei e os Profetas se resumem a estes dois mandamentos inseparáveis.',
  },
  {
    id: 'tc2-31', label: '31ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Contra a hipocrisia',
    description: '31ª semana do Tempo Comum.',
    reflection: 'Jesus critica os que "dizem e não fazem". A autêntica autoridade cristã é serviço: "O maior entre vós será o vosso servo" (Mt 23,11).',
  },
  {
    id: 'tc2-32', label: '32ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'As virgens prudentes',
    description: '32ª semana do Tempo Comum.',
    reflection: 'Cinco virgens levaram azeite; cinco não. Símbolo da vigilância cristã: não sabemos o dia nem a hora. O azeite é a graça acumulada em obras de fé e caridade.',
  },
  {
    id: 'tc2-33', label: '33ª semana', season: 'tempoComum', color: SEASON_COLORS.tempoComum,
    liturgicalColor: 'Verde', theme: 'Os talentos',
    description: '33ª semana do Tempo Comum. Dia Mundial dos Pobres (instituído pelo Papa Francisco).',
    reflection: 'Cada um recebe talentos segundo sua capacidade. Deus não pede o que não deu — mas cobra o uso do que confiou. Neste domingo, a Igreja se volta em especial aos pobres.',
  },
  {
    id: 'cristo-rei',
    label: 'Cristo Rei',
    season: 'tempoComum',
    color: WHITE,
    liturgicalColor: 'Branco',
    theme: 'Cristo, Rei do Universo',
    description: 'Solenidade de Nosso Senhor Jesus Cristo, Rei do Universo — último domingo do ano litúrgico.',
    reflection: 'A realeza de Cristo não é como a do mundo: é a do Servo Sofredor, do Bom Pastor, do Juiz misericordioso. "O que fizestes a um destes meus irmãos mais pequeninos, a mim o fizestes" (Mt 25,40). Encerramos o ano litúrgico contemplando o Rei que reinará para sempre.',
    readings: {
      firstReading: 'Ez 34,11-12.15-17 | Dn 7,13-14 | 2Sm 5,1-3',
      psalm: 'Sl 22',
      secondReading: '1Cor 15,20-26.28 | Ap 1,5-8 | Cl 1,12-20',
      gospel: 'Mt 25,31-46 | Jo 18,33b-37 | Lc 23,35-43',
    },
    prayer: 'Deus eterno e todo-poderoso, que quisestes renovar todas as coisas em Cristo, Rei do universo, fazei que toda a criação, liberta da escravidão, sirva à vossa majestade e vos glorifique eternamente.',
  },
];