export const meta = {
  nome: 'Santo Isidoro Lavrador',
  titulo: 'LEIGO · LAVRADOR · PADROEIRO DOS AGRICULTORES · PADROEIRO DE MADRI',
  subtitulo: '"Orai e trabalhai — e os anjos lavrarão convosco." — Tradição isidoriana',
  categoria: 'leigos',
  slug: 'sao-isidoro-lavrador',
  nascimento: 'c. 1070 — Madri, Reino de Castela',
  morte: '15 de maio de 1130 (ou 1172, segundo outras fontes) — Madri',
  canonizacao: '12 de março de 1622, pelo Papa Gregório XV',
  festa: '15 de maio',
  padroeiro: 'Agricultores, lavradores, camponeses, Madri, arquidiocese de Madri, trabalhadores rurais',
  atributos: 'Enxada, arado, boi, anjo lavrando, feixe de trigo, hábito de servo camponês',
  abas: [
    { slug: 'historia',         label: 'Vida' },
    { slug: 'contexto',         label: 'Contexto Histórico' },
    { slug: 'milagres',         label: 'Milagres em Vida' },
    { slug: 'espiritualidade',  label: 'Espiritualidade' },
    { slug: 'morte-corpo',      label: 'Morte e Corpo Incorrupto' },
    { slug: 'milagres-postumos', label: 'Milagres Póstumos' },
    { slug: 'canonizacao',      label: 'Beatificação e Canonização' },
    { slug: 'devocao',          label: 'Devoção e Culto' },
    { slug: 'patronato',        label: 'Patronato e Difusão Mundial' },
    { slug: 'liturgia',         label: 'Liturgia e Ofício' },
    { slug: 'iconografia',      label: 'Iconografia e Arte' },
    { slug: 'frases',           label: 'Antologia' },
    { slug: 'curiosidades',     label: 'Curiosidades' },
  ],
};