export const meta = {
  nome: 'São Tomás de Aquino',
  titulo: 'DOUTOR ANGÉLICO · PRÍNCIPE DOS TEÓLOGOS · LUZ DA IGREJA',
  subtitulo: '"Non aliam nisi Te, Domine." — tradição do Crucifixo de Nápoles',
  categoria: 'doutores',
  slug: 'sao-tomas-de-aquino',
  abas: [
    { slug: 'historia', label: 'História' },
    { slug: 'contexto', label: 'Contexto' },
    { slug: 'formacao', label: 'Formação' },
    { slug: 'magisterio', label: 'Magistério' },
    { slug: 'obras', label: 'Obras' },
    { slug: 'metodo', label: 'Método' },
    { slug: 'metafisica', label: 'Metafísica' },
    { slug: 'conhecimento', label: 'Conhecimento' },
    { slug: 'deus-e-criacao', label: 'Deus e Criação' },
    { slug: 'anjos-e-cosmos', label: 'Anjos e Cosmos' },
    { slug: 'homem-e-alma', label: 'Homem e Alma' },
    { slug: 'virtudes-e-moral', label: 'Virtudes e Moral' },
    { slug: 'lei-e-politica', label: 'Lei e Política' },

    { slug: 'cristo-e-redencao', label: 'Cristo e Redenção' },
    { slug: 'graca-e-predestinacao', label: 'Graça e Predestinação' },
    { slug: 'sacramentos-e-liturgia', label: 'Sacramentos e Liturgia' },
    { slug: 'escritura-e-exegese', label: 'Escritura e Exegese' },
    { slug: 'mariologia-e-santos', label: 'Mariologia e Santos' },
    { slug: 'mistica-e-oracao', label: 'Mística e Oração' },
    { slug: 'controversias', label: 'Controvérsias' },
    { slug: 'recepcao-e-tomismo', label: 'Recepção e Tomismo' },
    { slug: 'culto-e-canonizacao', label: 'Culto e Canonização' },
    { slug: 'reliquias-e-memoria', label: 'Relíquias e Memória' },
    { slug: 'milagres-e-devocoes', label: 'Milagres e Devoções' },
    { slug: 'frases', label: 'Frases' },
    { slug: 'iconografia', label: 'Iconografia' },
  ],
};