export const credo = {
  introducao: `O Concílio de Éfeso (431) não compôs um credo novo. Diferentemente de Niceia (325) e Constantinopla I (381), que produziram fórmulas de fé próprias, Éfeso limitou-se a reafirmar solenemente o Credo de Niceia (325) como norma única e irrevogável da fé cristã. Na Sessão I (22 de junho de 431), antes de qualquer deliberação sobre Nestório, os Padres conciliares mandaram ler publicamente o Credo niceno, estabelecendo-o como o padrão contra o qual os ensinamentos de Nestório seriam medidos. A leitura foi solene e simbólica: o Credo de 325 tornava-se o critério absoluto de ortodoxia cristológica.

Esta postura foi codificada juridicamente no célebre Cânon 7, que proibiu terminantemente a composição, apresentação ou ensino de qualquer "outra fé" (hetera pistis) além da definida em Niceia. A pena era severa: deposição para bispos e clérigos, excomunhão (anátema) para leigos. O cânon foi promulgado em resposta a uma denúncia específica — o presbítero Cárisio de Filadélfia (Lídia) apresentou ao Concílio uma "fórmula de fé" alternativa contendo os ensinamentos cristológicos de Teodoro de Mopsuéstia, que estava sendo usada por missionários nestorianos para receber convertidos do paganismo, judaísmo e outras heresias.

Historicamente, o Cânon 7 representou o fechamento do "cânon dos credos": após Éfeso, nenhuma nova fórmula batismal ou de conversão poderia ser criada, apenas exposições e defesas do Credo niceno. Esta decisão teria consequências monumentais para a história da Igreja, especialmente no que se refere ao estatuto do Credo Niceno-Constantinopolitano (381) e, séculos depois, à adição latina do Filioque.`,

  paradoxos: [
    'O Credo Niceno-Constantinopolitano (381) era tecnicamente uma "expansão" do Credo de 325 — adicionou artigos completos sobre o Espírito Santo, a Igreja, o batismo e a vida futura. Como conciliar sua existência e uso litúrgico com a proibição absoluta do Cânon 7 de "outros credos"? Este é o paradoxo fundamental que atravessou séculos de reflexão canônica.',
    'A resposta histórica dos Padres calcedonianos (451): o Cânon 7 visava especificamente o credo cristológico de Cárisio (que continha os ensinamentos de Teodoro de Mopsuéstia e Nestório), não credos homogêneos e legítimos que apenas explicitassem a fé de Niceia. O Credo de 381 é considerado uma "explicação" (ekthesis, explicatio) fiel de Niceia, não uma "outra fé" (hetera pistis).',
    'A distinção-chave que emerge da tradição: existe diferença fundamental entre (a) um "credo diferente" que contradiga ou substitua Niceia (proibido), e (b) uma "explicitação homogênea" que apenas desdobre e defenda a fé nicena contra novas heresias (permitido). Esta distinção, embora não formulada explicitamente em Éfeso, torna-se o critério interpretativo padrão da tradição.',
    'Curiosamente, o Credo de 381 só aparece oficialmente e por escrito em contexto conciliar 70 anos depois, no Concílio de Calcedônia (451), onde é lido e proclamado como confirmação de Niceia. Este atraso é conhecido pelos historiadores como o "problema do credo" (Kelly, Kinzig, Vinzent): há debate acadêmico sobre se o texto atualmente chamado "Niceno-Constantinopolitano" foi de fato composto em 381 ou apenas atribuído a Constantinopla I retrospectivamente.',
    'A distinção entre "novo credo" (proibido como heresia) e "explicação legítima" (permitida como ortodoxia) torna-se o critério hermenêutico fundamental para toda a evolução dogmática posterior. Todos os grandes desenvolvimentos doutrinais — cristológicos, marianos, sacramentais — são apresentados como "explicações" da fé apostólica contida em germe no Credo niceno.',
    'O Cânon 7 tornou-se, desde o século IX, a arma teológica principal do Oriente ortodoxo contra a adição ocidental do Filioque ("e do Filho") ao terceiro artigo do Credo. Para os ortodoxos, o Filioque é literalmente uma "outra fé" (hetera pistis) proibida por Éfeso; para os latinos, é uma "explicação" legítima homogênea à fé nicena. O debate permanece aberto até hoje.'
  ],

  relevanciaFilioque: `A relevância do Cânon 7 de Éfeso para a controvérsia do Filioque é imensa e permanente. Do ponto de vista ortodoxo oriental, a adição unilateral da cláusula "e do Filho" (Filioque) ao Credo Niceno-Constantinopolitano pelas igrejas do Ocidente latino — primeiro na Espanha visigótica (Toledo III, 589), depois no império franco (Concílio de Aachen, 809), e finalmente em Roma sob Bento VIII (~1014) — constitui violação flagrante e direta do Cânon 7 de Éfeso. Os teólogos ortodoxos, desde Fócio (Mystagogia do Espírito Santo, ~885) até Marcos de Éfeso no Concílio de Florença (1439) e teólogos contemporâneos como John Meyendorff e Vladimir Lossky, argumentam que o Filioque é literalmente uma "hetera pistis" — uma fé diferente — proibida pelo cânon efesino, e que sua introdução unilateral pelo Ocidente sem consulta ao Oriente é dupla violação: canônica (Cânon 7) e eclesiológica (unilateralismo).

A resposta católica romana, elaborada sistematicamente desde o Concílio de Florença (1439) e reafirmada em documentos recentes do Pontifício Conselho para a Unidade dos Cristãos (notadamente o esclarecimento de 1995 "As tradições grega e latina sobre a procissão do Espírito Santo"), é que o Filioque não é uma "outra fé" (hetera pistis) proibida pelo Cânon 7, mas uma "explicitação" (explicatio) legítima e homogênea da fé nicena, análoga aos artigos adicionados pelo Credo de 381 sobre o Espírito Santo. Argumentam ainda os latinos que a proibição visava credos que contradissessem Niceia (como o de Cárisio, com sua cristologia nestoriana), não desenvolvimentos consistentes com a fé apostólica.

No Concílio de Florença (1439), a delegação bizantina, liderada inicialmente por José II de Constantinopla e teologicamente por Bessarion e Marcos de Éfeso, debateu intensamente esta questão. A maioria acabou aceitando a fórmula latina, mas Marcos de Éfeso permaneceu firme na recusa, apelando explicitamente ao Cânon 7 de Éfeso. Após seu regresso ao Oriente, a maioria bizantina repudiou a União de Florença, e a interpretação de Marcos tornou-se dominante na Ortodoxia. Até hoje, o Filioque permanece um dos principais pontos de divisão entre a Igreja Católica Romana e as Igrejas Ortodoxas, e o Cânon 7 de Éfeso é invocado em praticamente todos os documentos ortodoxos sobre o assunto. Diálogos ecumênicos recentes têm buscado formulações que preservem tanto a legitimidade da tradição latina quanto a integridade canônica invocada pelo Oriente, sem que se tenha chegado a consenso definitivo.`
}