export const resumoRecepcao = `A recepção do Concílio de Éfeso foi complexa, tumultuada e gradual, estendendo-se por séculos e envolvendo desde reconciliações doutrinais dolorosas até cismas duradouros que perduram até hoje. Diferentemente do que sugere uma leitura idealizada dos concílios ecumênicos, Éfeso não foi imediatamente aceito por todas as partes: houve um cisma de dois anos entre Alexandria e Antioquia (431–433), longos debates sobre a legitimidade dos Doze Anátemas de Cirilo (só definitivamente confirmados em 553), e a formação da Igreja Persa nestoriana como cristianismo alternativo fora do Império Romano.

A linha do tempo abaixo traça os principais momentos da recepção efesina, do imediato pós-concílio (431–433) até os diálogos ecumênicos contemporâneos (1994 e presente), mostrando como um concílio inicialmente contestado tornou-se um dos pilares indiscutíveis da fé cristológica cristã.`

export const recepcao = [
  {
    periodo: '431–433',
    titulo: 'O Cisma Cirilo–João de Antioquia',
    descricao: 'Após o Concílio, Cirilo de Alexandria e João de Antioquia permaneceram em ruptura mútua por quase dois anos. Cirilo havia deposto Nestório na Sessão I (22 de junho de 431); João realizara contra-concílio depondo Cirilo e Memnon de Éfeso (26 de junho de 431). Ambos os grupos trocavam anátemas, cartas polêmicas e apelos ao imperador. Teodósio II inicialmente ratificou AMBAS as deposições, prendendo Cirilo, Memnon e Nestório simultaneamente. A situação era juridicamente caótica e teologicamente insustentável. Cirilo conseguiu escapar da prisão em outubro de 431 e voltou triunfalmente a Alexandria; João de Antioquia manteve seu bloco "oriental" em resistência. Múltiplas embaixadas foram trocadas entre Alexandria, Antioquia, Constantinopla e Roma, com pressão crescente da corte imperial e do papa Sisto III (sucessor de Celestino I) por reconciliação. Teodoreto de Ciro, Acácio de Beroia e outros teólogos moderados atuaram como mediadores.',
    importancia: 'Demonstra que a decisão conciliar, mesmo quando substantivamente correta, requer processo prolongado de recepção. A "receptio" ecumênica não é decreto instantâneo mas processo histórico complexo.'
  },
  {
    periodo: '433',
    titulo: 'A Fórmula de União (Symbolum Ephesinum)',
    descricao: 'Em abril de 433, após intensa mediação diplomática, Cirilo de Alexandria e João de Antioquia assinaram a Fórmula de União (também chamada "Symbolum Ephesinum" ou "Fórmula de Reunião"), texto redigido originalmente por Teodoreto de Ciro e ligeiramente modificado por Cirilo. A Fórmula é um compromisso teológico notável: mantém integralmente o título Theotokos ("confessamos que a Santa Virgem é Theotokos, pois o Deus Verbo se encarnou e se fez homem"), afirma explicitamente a existência de duas naturezas em Cristo unidas em uma única pessoa/prosōpon ("a união das duas naturezas se realizou; por isso confessamos um só Cristo, um só Filho, um só Senhor"), e reconhece a comunicação das propriedades. Cirilo enviou a João a carta "Laetentur caeli" ("Alegrem-se os céus"), oficializando a reconciliação. João, por sua vez, aceitou publicamente a deposição de Nestório.',
    importancia: 'Marco histórico e teológico monumental. A Fórmula de União tornou-se, na prática, a formulação cristológica que Calcedônia (451) explicitaria e ampliaria dezoito anos depois. É modelo permanente de compromisso ecumênico: linguagem ciriliana (unidade de pessoa, Theotokos) integrada com linguagem antioquena (duas naturezas), formando síntese ortodoxa. Historicamente, marca o fim do cisma imediato de 431 e a reintegração da maior parte dos "orientais" na comunhão com Cirilo e Roma.'
  },
  {
    periodo: '444',
    titulo: 'Morte de Cirilo e ascensão de Dióscoro em Alexandria',
    descricao: 'Em 27 de junho de 444, morreu Cirilo de Alexandria após 32 anos de patriarcado. Foi sucedido por seu arquidiácono Dióscoro (444–451), que herdou o prestígio da vitória efesina mas radicalizou a cristologia ciriliana de modo problemático. Enquanto Cirilo, especialmente após 433, aceitava a linguagem das "duas naturezas" desde que subordinada à unidade de pessoa, Dióscoro passou a rejeitar categoricamente qualquer linguagem de "duas naturezas" após a união, insistindo exclusivamente na fórmula "uma natureza encarnada". Sob sua liderança, Alexandria tornou-se centro do que viria a ser chamado de monofisismo (ou, mais precisamente, miafisismo). Dióscoro apoiou ativamente o arquimandrita constantinopolitano Eutiques, que ensinava explicitamente que a humanidade de Cristo foi "absorvida" pela divindade "como uma gota de mel no oceano".',
    importancia: 'Ponto de inflexão negativo. A radicalização ciriliana pós-Cirilo prepararia a crise monofisita, o Latrocínio de Éfeso (449), o Concílio de Calcedônia (451) e o cisma pós-calcedoniano que persiste até hoje entre calcedonianos e não-calcedonianos.'
  },
  {
    periodo: '449',
    titulo: 'O Latrocínio de Éfeso (Ephesus II) — o "Concílio de Ladrões"',
    descricao: 'Em agosto de 449, o imperador Teodósio II convocou segundo concílio em Éfeso, presidido por Dióscoro de Alexandria, para tratar da controvérsia sobre Eutiques (que havia sido condenado em sínodo local em Constantinopla, em 448, por Flaviano de Constantinopla). O concílio foi conduzido de modo extremamente irregular e violento: Dióscoro impediu a leitura do Tomo do papa Leão I a Flaviano (o famoso "Tomus ad Flavianum"), reabilitou Eutiques e depôs Flaviano de Constantinopla, Domno de Antioquia, Teodoreto de Ciro e Ibas de Edessa. Flaviano foi tão violentamente agredido por partidários de Dióscoro (incluindo monges egípcios armados) que morreu poucos dias depois em consequência dos ferimentos. Quando as atas chegaram a Roma, o papa Leão I reagiu com veemência histórica, chamando o concílio de "non iudicium sed latrocinium" — "não juízo, mas roubo" (Epistola 95). A alcunha "Latrocínio de Éfeso" (Latrocinium Ephesinum) pegou.',
    importancia: 'Momento mais sombrio da recepção efesina. Mostra como uma cristologia originalmente ortodoxa (a ciriliana) pode ser distorcida em direção herética quando desligada de seus contrapesos (afirmação da humanidade completa e distinta). Provoca reação decisiva de Roma e prepara o terreno para Calcedônia.'
  },
  {
    periodo: '451',
    titulo: 'Concílio de Calcedônia — o IV Concílio Ecumênico',
    descricao: 'Após a morte de Teodósio II em julho de 450 (por queda de cavalo) e a ascensão de Marciano com Pulquéria (que se casou com ele para legitimar sua sucessão), o novo regime imperial convocou grande concílio em Calcedônia (perto de Constantinopla), realizado de 8 de outubro a 1º de novembro de 451, com aproximadamente 520 bispos — o maior concílio da Antiguidade cristã. Calcedônia fez cinco coisas fundamentais: (1) anulou integralmente o Latrocínio de Éfeso (449); (2) restabeleceu postumamente Flaviano de Constantinopla e reabilitou Teodoreto de Ciro e Ibas de Edessa; (3) depôs Dióscoro de Alexandria; (4) confirmou solenemente Éfeso 431 e a autoridade dos Doze Anátemas de Cirilo; (5) formulou a definição cristológica clássica: "um só e mesmo Cristo, Filho, Senhor, Unigênito, reconhecido em duas naturezas (en dyo physesin), sem confusão, sem mudança, sem divisão, sem separação (asynchytōs, atreptōs, adiairetōs, achōristōs) — a diferença das naturezas não é de modo algum abolida pela união, mas antes a propriedade de cada natureza é preservada e concorre em uma só pessoa (prosōpon) e uma só hipóstase (hypostasis)".',
    importancia: 'Completa e explicita Éfeso, formando com ele a síntese cristológica clássica. Rejeita simultaneamente o nestorianismo (dois sujeitos) e o monofisismo (uma natureza confusa). Torna-se o marco doutrinal fundamental para católicos, ortodoxos bizantinos, anglicanos e luteranos. Mas simultaneamente provoca o cisma pós-calcedoniano com Egito, Síria ocidental, Armênia e Etiópia, que rejeitam a fórmula "em duas naturezas" como traição à linguagem ciriliana.'
  },
  {
    periodo: '553',
    titulo: 'II Concílio de Constantinopla e a controvérsia dos Três Capítulos',
    descricao: 'Sob o imperador Justiniano I (527–565), que buscava reintegrar os não-calcedonianos ao Império, foi convocado o V Concílio Ecumênico em Constantinopla (5 de maio a 2 de junho de 553), com 168 bispos. O concílio condenou postumamente os chamados "Três Capítulos": (1) a pessoa e escritos de Teodoro de Mopsuéstia, considerado a raiz teológica do nestorianismo; (2) os escritos de Teodoreto de Ciro contra os Doze Anátemas de Cirilo; (3) a Carta de Ibas de Edessa a Maris o Persa. O objetivo era mostrar aos não-calcedonianos que Calcedônia não havia reabilitado o nestorianismo. Simultaneamente, o concílio confirmou solenemente os Doze Anátemas de Cirilo como ortodoxos e aprovou a fórmula teopaschita ("um da Trindade sofreu na carne").',
    importancia: 'Marca a "interpretação ciriliana de Calcedônia": Calcedônia deve ser lida em continuidade com Éfeso e Cirilo, não como sua correção antioquena. Consolida definitivamente os Doze Anátemas como magistério ortodoxo. Mas fracassa no objetivo de reconciliar os não-calcedonianos, que permanecem em cisma até hoje.'
  },
  {
    periodo: 'Séc. IX–XI',
    titulo: 'A Controvérsia do Filioque e o Cânon 7 de Éfeso',
    descricao: 'A adição da cláusula "Filioque" ("e do Filho") ao Credo pela Igreja latina tornou-se o principal ponto de tensão Roma-Constantinopla. O Cânon 7 de Éfeso (proibição de novos credos) foi invocado sistematicamente pelos ortodoxos contra a adição. Marcos: 809 Concílio de Aachen (Carlos Magno adota o Filioque contra Leão III); 858-867 Fócio e sua Mystagogia atacam o Filioque como violação do Cânon 7; ~1014 Bento VIII insere oficialmente o Filioque em Roma sob Henrique II; 1054 Grande Cisma; 1439 Florença — Marcos de Éfeso apela ao Cânon 7 para rejeitar o Filioque, posição que se torna dominante na Ortodoxia.',
    importancia: 'Mostra a longevidade normativa do Cânon 7: uma proibição disciplinar de 431 torna-se argumento trinitário decisivo mil anos depois.'
  },
  {
    periodo: 'Séc. XVI',
    titulo: 'A Recepção de Éfeso na Reforma Protestante',
    descricao: 'Lutero aceitava Éfeso e a Theotokos como bíblica (Lc 1,43; Das Marienlied, 1521: "Maria é verdadeira Mãe de Deus"), mas rejeitava culto excessivo — Theotokos é afirmação sobre Cristo. Calvino aceitava formalmente o título mas rejeitava o culto mariano pós-efesino (Psychopannychia 1534; Institutas): 431 foi correto, a posteridade distorceu em idolatria. A Igreja da Inglaterra (Artigo XXI, 1562/1571) subordinou concílios à Escritura: "podem errar, e às vezes erraram".',
    importancia: 'Revela recepção ambivalente: dogma cristológico mantido, piedade mariana criticada — distinção entre Éfeso dogmático e desenvolvimentos posteriores.'
  },
  {
    periodo: 'Séc. XVII–XVIII',
    titulo: 'Éfeso na Escolástica e na Contrarreforma',
    descricao: 'Trento (1545-1563) reafirmou implicitamente Éfeso ao confirmar concílios ecumênicos. Suárez, Belarmino e Melchor Cano integraram Éfeso nos "loca theologica" como fonte dogmática. A mariologia moderna (Imaculada 1854; Assunção 1950) fundamenta-se no princípio efesino: se Maria é Theotokos, seus privilégios são consequências da Encarnação.',
    importancia: 'Consolida Éfeso como fundamento da mariologia sistemática católica posterior.'
  },
  {
    periodo: '1962–1965',
    titulo: 'O Concílio Vaticano II e a Theotokos',
    descricao: 'O Concílio Vaticano II (1962–1965) tratou da Theotokos no capítulo 8 da constituição dogmática Lumen Gentium (1964). A decisão de incluir Maria no documento sobre a Igreja (e não em documento separado) foi uma das decisões mais significativas e mais debatidas do Concílio. A maioria dos Padres conciliares, seguindo a orientação de Paulo VI, decidiu que Maria deveria ser tratada eclesiológica e cristologicamente — não isoladamente como "devoção mariana". A Lumen Gentium afirma: "Maria, Mãe de Deus, é reconhecida e venerada como verdadeira Mãe de Deus e do Redentor... Unida a Cristo na glória celestial, ela intercede junto ao Pai como mãe da graça" (LG 62). Esta formulação é uma reafirmação direta de Éfeso: Maria é Mãe de Deus (Theotokos) porque é Mãe de Cristo, que é Deus. O Concílio também reafirmou que o culto mariano "diferindo por natureza do culto de adoração, que é dado ao Verbo Encarnado, ao Pai e ao Espírito Santo, é de grande eficácia para fomentar" a fé (LG 66).',
    importancia: 'O Vaticano II é a recepção mais recente de Éfeso em nível conciliar. Ao subordinar a mariologia à cristologia e à eclesiologia, o Concílio reafirmou o princípio fundamental de Éfeso: a Theotokos é uma afirmação sobre Cristo, não uma exaltação isolada de Maria. A decisão de não definir novos dogmas marianos (como a proposta de "Maria Corredentora") reflete também o espírito do Cânon 7: a Igreja não deve multiplicar definições além do necessário. Fontes: Concílio Vaticano II, Lumen Gentium, caps. 8 (1964); René Laurentin, The Question of Mary (1965); Luigi Gambero, Mary and the Fathers of the Church (1999).'
  },
  {
    periodo: '1994',
    titulo: 'Declaração Cristológica Comum (João Paulo II e Mar Dinkha IV)',
    descricao: 'Em 11 de novembro de 1994, no Vaticano, o papa João Paulo II e o Catholicos-Patriarca Mar Dinkha IV, da Igreja Assíria do Oriente, assinaram a "Declaração Cristológica Comum entre a Igreja Católica e a Igreja Assíria do Oriente". O documento reconhece que a fé cristológica das duas tradições, embora expressa em vocabulários diferentes (a Igreja Assíria evita o título "Theotokos" como tal, mas confessa Maria como "Mãe de Cristo nosso Deus e Salvador"), é substancialmente a mesma: uma união real e permanente entre a divindade e a humanidade em Cristo. Cada tradição reconhece a fé ortodoxa da outra e as excomunhões mútuas do séc. V são declaradas superadas. A declaração foi complementada em 2001 pela "Diretriz para Admissão à Eucaristia entre a Igreja Caldeia e a Igreja Assíria do Oriente", permitindo intercomunhão sacramental em certas circunstâncias.',
    importancia: 'Marco histórico monumental. Supera 1563 anos de mútua excomunhão que datam de Éfeso (431). Mostra que a interpretação polêmica da controvérsia efesina foi em grande parte terminológica, e que reconciliação teológica é possível quando cada tradição reconhece o núcleo ortodoxo da preocupação da outra.'
  },
  {
    periodo: 'Atualidade (séc. XXI)',
    titulo: 'Recepção ecumênica contemporânea de Éfeso',
    descricao: 'Éfeso 431 é atualmente aceito como concílio ecumênico legítimo por praticamente todas as grandes tradições cristãs históricas: Igreja Católica Romana, Igrejas Ortodoxas Bizantinas (Constantinopla, Alexandria grega, Antioquia grega, Jerusalém, Rússia, Sérvia, Romênia, Bulgária, Geórgia, Chipre, Grécia, Polônia, Albânia, República Tcheca e Eslováquia), Igrejas Ortodoxas Orientais não-calcedonianas (Igreja Copta, Igreja Siríaca Ortodoxa, Igreja Apostólica Armênia, Igreja Ortodoxa Etíope, Igreja Ortodoxa Eritreia, Igreja Siríaca Malankara), Comunhão Anglicana, Federação Luterana Mundial, várias igrejas reformadas históricas. A Theotokos é dogma aceito por todos estes grupos, embora com ênfases devocionais diferentes. Diálogos ecumênicos multilaterais em curso — notadamente o diálogo católico-ortodoxo (Comissão Mista Internacional), o diálogo católico-oriental, o diálogo com a Igreja Assíria — continuam a explorar as implicações contemporâneas de Éfeso para a unidade cristã. O Filioque permanece o principal ponto pendente, ligado ao Cânon 7.',
    importancia: 'Éfeso emerge no séc. XXI paradoxalmente como ponto de convergência ecumênica, não de divisão. A pesquisa histórico-teológica moderna, o diálogo respeitoso entre tradições e a superação de caricaturas polêmicas revelaram profunda unidade cristológica subjacente às divergências terminológicas históricas.'
  }
]