export const meta = {
  nome: 'São Domingos Sávio',
  titulo: 'ADOLESCENTE · DISCÍPULO DE DOM BOSCO · PATRONO DOS COROINHAS',
  subtitulo: '"Antes morrer do que pecar" — Lema de vida',
  categoria: 'leigos',
  slug: 'sao-domingos-savio',
  nascimento: '2 de abril de 1842 — San Giovanni di Riva, Piemonte, Itália',
  falecimento: '9 de março de 1857 — Mondonio, Piemonte, Itália (14 anos)',
  beatificacao: '5 de março de 1950 — Pio XII',
  canonizacao: '12 de junho de 1954 — Pio XII',
  festa: '6 de maio',
  patronato: 'Coroinhas, adolescentes, meninos de coro, pueris cantores',
  abas: [
    { slug: 'historia',            label: 'História' },
    { slug: 'familia',             label: 'Família' },
    { slug: 'infancia',            label: 'Infância' },
    { slug: 'valdocco',            label: 'Valdocco' },
    { slug: 'espiritualidade',     label: 'Espiritualidade' },
    { slug: 'companhiaimaculada',  label: 'Companhia da Imaculada' },
    { slug: 'episodios',           label: 'Episódios' },
    { slug: 'doencaemorte',        label: 'Doença e Morte' },
    { slug: 'frases',              label: 'Frases' },
    { slug: 'teologia',            label: 'Teologia' },
    { slug: 'canonizacao',         label: 'Canonização' },
    { slug: 'culto',               label: 'Culto' },
    { slug: 'legado',              label: 'Legado' },
  ],
};
