export const introducaoHonorio =
  "O anátema contra o Papa Honório I (625–638) é o evento mais controverso do Concílio de Constantinopla III e um dos episódios mais debatidos em toda a história da Igreja. Trata-se do ÚNICO caso na história em que um papa foi formalmente anatematizado por um concílio ecumênico — uma condenação aceita, ainda que com nuances interpretativas cruciais, pelo próprio papado através da carta de confirmação do Papa Leão II em 682. O caso Honório atravessou os séculos como o argumento mais frequentemente citado contra a infalibilidade papal e reapareceu com força dramática durante o Concílio Vaticano I (1869–1870), quando a definição do dogma da infalibilidade teve que ser cuidadosamente formulada para acomodar este precedente histórico. Compreender o caso Honório com precisão exige distinguir o que ele efetivamente disse, o que ele NÃO disse, o que o concílio precisamente condenou, e como o próprio papado interpretou essa condenação — pois a resposta a estas quatro perguntas determina toda a interpretação subsequente do episódio."

export const contextoHonorio =
  "Em 634, o patriarca Sérgio I de Constantinopla — arquiteto do monoenergismo e, posteriormente, do monotelismo — enviou uma carta ao Papa Honório I relatando a controvérsia gerada pelo Pacto de União de Alexandria (633) e pela oposição de Sofrônio de Jerusalém. Sérgio apresentou a questão de modo tendencioso: descreveu o sucesso pastoral do monoenergismo em atrair miafisitas de volta à comunhão, apresentou a oposição de Sofrônio como excessivo rigorismo terminológico, e formulou a pergunta central de forma capciosa — se era lícito falar de 'uma' ou 'duas' operações em Cristo, sugerindo que ambas as fórmulas eram problemáticas e que o melhor seria evitar totalmente a discussão. Honório, papa de perfil predominantemente pastoral (não teólogo especulativo), respondeu em 634 ou início de 635 com duas cartas. Sua preocupação central era pastoral: evitar uma nova cisão eclesiástica sobre terminologia. Ele acatou a sugestão de Sérgio de proibir a discussão sobre 'uma ou duas operações' e, ao tratar da questão volitiva, empregou a fatídica expressão 'confessamos uma vontade de nosso Senhor Jesus Cristo' (ἓν θέλημα ὁμολογοῦμεν τοῦ Κυρίου ἡμῶν Ἰησοῦ Χριστοῦ, unam voluntatem fatemur Domini nostri Iesu Christi). Uma segunda carta, mais cautelosa, matizou a primeira. Sérgio recebeu ambas com entusiasmo e as instrumentalizou: doravante, o monotelismo tinha respaldo papal explícito. Quatro anos depois, quando Heráclio promulgou o Ecthesis (638) impondo o monotelismo como doutrina oficial do Império, a carta de Honório foi um dos documentos justificativos. Honório havia morrido pouco antes (12 de outubro de 638), sem ver as consequências históricas de sua tentativa de mediação pastoral."

export const oQueHonorioDisse =
  "O texto crítico da primeira carta de Honório a Sérgio, preservado nas atas do concílio (ACO II.2), contém a passagem decisiva: 'Confessamos uma só vontade de nosso Senhor Jesus Cristo, pois manifestamente foi a divindade que assumiu a nossa natureza, não o vício que nela habita — isto é, a natureza que foi criada antes do pecado, não aquela que foi corrompida depois da transgressão.' A frase-chave 'unam voluntatem fatemur' aparece explicitamente. Contudo, o contexto imediato mostra que Honório NÃO está usando 'vontade' no sentido técnico de faculdade natural (thelema physikon) — o sentido em que Máximo, o Confessor, e o concílio empregariam o termo. Honório está afirmando que em Cristo não há CONFLITO de vontades, não há a luta entre a vontade da carne caída e a vontade do espírito que caracteriza a experiência humana pós-lapsária. Sua 'una voluntas' é uma unidade MORAL e HARMÔNICA (não há duas orientações opostas em Cristo), não uma unidade ONTOLÓGICA (não há uma só faculdade volitiva). Isto fica claro pelo próprio argumento que apresenta: Cristo assumiu a natureza humana criada por Deus, não a natureza humana corrompida pelo pecado; portanto, nele não há a divisão entre 'lei da carne' e 'lei do espírito' (cf. Rm 7,22-23). Honório também proibiu explicitamente a discussão terminológica sobre 'uma ou duas operações', afirmando que 'não devemos definir uma ou duas operações' e que tais debates 'pertencem aos gramáticos, não aos pregadores'. Sua intenção declarada era pastoral: silenciar a controvérsia, não definir dogma."

export const oQueHonorioNaoDisse =
  "É crucial distinguir o que Honório efetivamente disse do que se atribuiu a ele. Honório NUNCA negou as duas naturezas de Cristo — pelo contrário, sua carta pressupõe integralmente Calcedônia. Honório NUNCA usou linguagem tecnicamente monotelita no sentido de Sérgio ou Macário; ele não conhecia os desenvolvimentos teológicos do monoenergismo em profundidade e respondia a uma pergunta pastoral com resposta pastoral. Honório NUNCA pretendeu definir um dogma ex cathedra: sua carta era uma resposta privada a uma consulta episcopal, não uma encíclica dirigida à Igreja universal, não uma constituição dogmática, não uma definição solene. Honório NUNCA usou as formas canônicas da definição dogmática papal (invocação da autoridade apostólica, intenção manifesta de obrigar toda a Igreja, fórmulas anatemáticas contra os que dissentissem). Honório NUNCA sustentou que a vontade humana de Cristo fosse absorvida ou substituída pela divina — questão que ele simplesmente não abordou. Honório NUNCA rejeitou a doutrina das duas vontades — questão que, à época de sua carta, ainda não havia sido formulada com precisão técnica (Máximo articularia a distinção apenas na década seguinte). O que Honório fez, precisamente, foi: (1) usar uma expressão infeliz ('una voluntas') em sentido moral que seria posteriormente instrumentalizada em sentido técnico monotelita; (2) proibir a discussão terminológica que teria permitido esclarecer a questão; (3) endossar, por omissão de correção, a linha teológica de Sérgio quando deveria tê-la corrigido. Sua culpa é, portanto, de NEGLIGÊNCIA PASTORAL (por omissão) e de IMPRUDÊNCIA TERMINOLÓGICA (por comissão), não de HERESIA FORMAL (por ensino positivo de erro doutrinário)."

export const aCondenacaoNoConcilio =
  "Na 11ª sessão do concílio (6 de abril de 681), as duas cartas de Sérgio a Honório e as duas cartas de Honório a Sérgio foram lidas na íntegra diante da assembleia. A leitura foi realizada com solenidade máxima: eram documentos do papa reinante quatro décadas antes, examinados publicamente por um concílio ecumênico. A reação foi de consternação silenciosa. Notavelmente, os TRÊS LEGADOS PAPAIS (Teodoro, Jorge e João, representantes de Roma) NÃO SE OPUSERAM à leitura, NÃO DEFENDERAM Honório e NÃO PROTESTARAM contra o exame de seu antecessor. Esse silêncio dos legados é historicamente decisivo: sugere fortemente que suas instruções de Roma previam a possibilidade da condenação de Honório e que Agatão I (falecido em janeiro de 681, durante o concílio) e a Cúria Romana consideravam defensável ou mesmo necessária a censura da conduta de Honório. Na 12ª sessão (19 de abril), o debate se aprofundou. Alguns bispos argumentaram que Honório usara 'vontade' em sentido moral, não técnico; outros responderam que, independentemente da intenção, o efeito prático da carta fora legitimar o monotelismo e comprometer a fé apostólica. Na 13ª sessão (28 de abril de 681), o anátema foi formalmente pronunciado. O Horos, aprovado meses depois, incluiu Honório na lista dos heresiarcas condenados com a seguinte formulação: 'Anatematizamos também Honório, que foi papa da antiga Roma, porque encontramos em sua carta a Sérgio que ele seguiu em tudo a mente deste e confirmou seus dogmas ímpios.' Note-se a precisão linguística: Honório é condenado por 'seguir a mente' e 'confirmar os dogmas' de Sérgio — ou seja, por ADESÃO PASSIVA e CONFIRMAÇÃO DE ERRO ALHEIO, não por ensino positivo próprio. A distinção é sutil mas juridicamente crucial: Honório é anatematizado como CÚMPLICE de Sérgio, não como HERESIARCA autônomo."

export const aInterpretacaoDeLeaoII =
  "O Papa Leão II (elegido em janeiro de 682, consagrado em agosto do mesmo ano após a demora imperial na confirmação) enfrentou a delicadíssima questão de confirmar ou não as atas de um concílio que anatematizara seu antecessor. Sua decisão foi historicamente decisiva: CONFIRMOU integralmente o concílio, incluindo o anátema contra Honório, MAS com uma REINTERPRETAÇÃO NUANCIADA que se tornaria a base de toda a leitura católica posterior do caso. Na carta de confirmação ao imperador Constantino IV (PL 96.399-404), Leão II escreveu: 'Anatematizamos os inventores do novo erro, isto é, Teodoro, Sérgio, Pirro, Paulo, Pedro, Ciro, e também Honório, que não iluminou esta Igreja Apostólica com o ensino da tradição apostólica, mas PERMITIU que a fé imaculada fosse subvertida por uma traição profana' (qui hanc apostolicam ecclesiam non apostolicae traditionis doctrina lustravit, sed profana proditione immaculatam fidem subvertere conatus est). O verbo é decisivo: 'permitiu' (permisit), não 'ensinou' (docuit). Numa segunda carta, dirigida aos bispos da Hispânia (PL 96.414 ss), Leão II foi ainda mais explícito: 'Honório, que não extinguiu no início a chama da doutrina herética, como convinha à autoridade apostólica, mas a alimentou por NEGLIGÊNCIA' (qui hanc apostolicam sedem non praedicatione apostolicae traditionis illustravit, sed profana proditione immaculatam fidem subvertere permisit, et flammam haeretici dogmatis, non ut decuit apostolicam auctoritatem, incipientem extinxit, sed negligendo confovit). As palavras-chave são NEGLIGÊNCIA (negligentia) e PERMISSÃO (permissio) — CATEGORIAS DE OMISSÃO, não de ensino positivo. Leão II, portanto, aceitou o anátema mas o reinterpretou substancialmente: Honório é condenado não por ter ensinado a heresia, mas por ter FALHADO em condená-la quando deveria tê-lo feito, e por ter usado linguagem ambígua que permitiu sua propagação. Esta reinterpretação — condenação por negligência, não por ensino — tornou-se a interpretação católica oficial e sobreviveu como tal por treze séculos, até ser formalmente invocada no Vaticano I."

export const oDebateNoVaticanoI =
  "Quando o Concílio Vaticano I se reuniu em 1869–1870 para definir a infalibilidade papal, o caso Honório ressurgiu como o argumento mais formidável dos oponentes da definição. A MINORIA anti-infalibilista — composta pelos galicanos franceses, pelos católicos alemães liderados por Döllinger, pelos bispos húngaros, austríacos e norte-americanos que consideravam a definição inoportuna — invocou Honório como PROVA HISTÓRICA de que papas podiam errar em matéria de fé e serem publicamente condenados por concílios ecumênicos. O argumento era simples e devastador: se Honório foi anatematizado por um concílio ecumênico como cúmplice de heresia, e se o próprio Leão II confirmou este anátema, então ou (a) os papas podem errar em matéria de fé (o que contradiz a infalibilidade), ou (b) o VI Concílio Ecumênico e Leão II erraram ao condenar um papa ortodoxo (o que abala a autoridade conciliar). Bispo Josip Strossmayer (Bósnia) e Lord Acton foram os principais articuladores desta objeção. A MAIORIA infalibilista — liderada pelo cardeal Manning e apoiada indiretamente por Newman (embora Newman preferisse uma definição minimalista) — respondeu com quatro argumentos convergentes: (1) Honório respondeu como DOUTOR PRIVADO em correspondência pastoral, não ex cathedra como pastor supremo da Igreja universal — sua carta a Sérgio não tem NENHUMA das características formais de uma definição solene; (2) Sua condenação foi por NEGLIGÊNCIA e IMPRUDÊNCIA, não por ensino positivo de erro — como o próprio Leão II precisou; (3) A infalibilidade papal, tal como será definida, aplica-se APENAS a definições solenes ex cathedra em matéria de fé e moral com intenção manifesta de obrigar toda a Igreja — condições que a carta de Honório manifestamente não preenche; (4) O próprio fato de o concílio ter examinado e julgado a carta prova que ela NÃO era ex cathedra — pois uma definição infalível é, por natureza, IRREFORMÁVEL e não pode ser julgada por concílio posterior. O texto final da Constituição Pastor Aeternus (18 de julho de 1870) incorporou essas nuances com precisão cirúrgica: definiu que o papa é infalível 'quando fala ex cathedra, isto é, quando, exercendo o ofício de pastor e doutor de todos os cristãos, em virtude de sua suprema autoridade apostólica, DEFINE uma doutrina sobre fé ou moral a ser sustentada por toda a Igreja' (Denz. 3074). As três condições — falar como pastor universal, invocar a autoridade apostólica suprema, definir com intenção obrigatória — excluem categoricamente a carta pastoral de Honório e neutralizam a objeção histórica. O caso Honório, portanto, não invalidou a infalibilidade, mas contribuiu decisivamente para sua formulação PRECISA e RESTRITA."

export const posicoesModernas = [
  {
    tradicao: "Posição Católica",
    posicao:
      "Honório foi negligente e imprudente, não herético formal. Sua condenação pelo concílio e por Leão II foi por OMISSÃO (não condenar o erro que devia ter condenado) e por AMBIGUIDADE TERMINOLÓGICA (usar 'una voluntas' de modo pastoralmente perigoso), não por ensino positivo de heresia. Sua carta a Sérgio NÃO foi ex cathedra: era resposta pastoral privada a consulta episcopal, sem as características formais de definição solene (não invocava autoridade apostólica suprema, não definia doutrina, não pretendia obrigar toda a Igreja, não continha fórmulas anatemáticas). Portanto, o caso Honório NÃO invalida o dogma da infalibilidade papal definido no Vaticano I, precisamente porque este dogma se aplica apenas a definições ex cathedra que a carta de Honório manifestamente não é. Teólogos como Joseph Ratzinger, Klaus Schatz e Jean-Marie Tillard defendem que o caso Honório, longe de refutar a infalibilidade, contribuiu para sua formulação precisa e restrita. A tradição católica reconhece plenamente o anátema histórico contra Honório e o lê à luz da reinterpretação nuanciada de Leão II.",
  },
  {
    tradicao: "Posição Ortodoxa",
    posicao:
      "O caso Honório prova que papas podem errar em matéria de fé e que os concílios ecumênicos possuem autoridade suprema, superior à do papa individualmente considerado. A doutrina da infalibilidade papal, tal como definida no Vaticano I, é considerada pela teologia ortodoxa como uma INOVAÇÃO medieval e moderna, incompatível com a prática eclesial dos sete primeiros concílios ecumênicos, os quais julgaram e condenaram bispos de todas as sedes patriarcais, incluindo Roma. A ortodoxia aceita integralmente o anátema contra Honório sem as nuances interpretativas católicas: para os teólogos ortodoxos (Meyendorff, Ware, Zizioulas, Romanides), Honório foi condenado como HERESIARCA, não meramente como negligente, e a distinção posterior de Leão II é vista como tentativa apologética para preservar a reputação papal. O caso é frequentemente invocado no diálogo ecumênico católico-ortodoxo como demonstração de que a eclesiologia do primeiro milênio era CONCILIAR, não papal.",
  },
  {
    tradicao: "Posição Protestante",
    posicao:
      "O caso Honório demonstra a FALIBILIDADE de toda autoridade eclesiástica humana — papado incluído — e reforça o princípio protestante da SOLA SCRIPTURA como norma última e infalível da fé cristã. Historiadores protestantes clássicos (Schaff, Harnack, von Döllinger após sua excomunhão) enfatizam que Honório foi genuinamente monotelita segundo o padrão de sua época e que sua condenação por um concílio ecumênico prova que nem papas nem concílios estão isentos de erro. A tradição luterana, reformada e anglicana aceita as decisões cristológicas de Constantinopla III (duas vontades e duas operações) como bíblicas e ortodoxas, mas rejeita qualquer pretensão de infalibilidade das instituições eclesiásticas humanas. Alguns teólogos protestantes contemporâneos (Oberman, McGrath) reconhecem que a distinção entre ensino ex cathedra e opinião privada, embora legítima em si mesma, foi desenvolvida ad hoc para preservar a infalibilidade papal após o Vaticano I.",
  },
  {
    tradicao: "Posição Acadêmica (Historiadores Seculares e Ecumênicos)",
    posicao:
      "A historiografia acadêmica contemporânea (Hovorun, Bathrellos, Allen, Louth, Price) tende a uma posição diferenciada. Reconhece que Honório PROVAVELMENTE não era monotelita no sentido técnico que o termo adquiriria após Máximo — sua carta reflete uma teologia pré-monotelita ambígua, mais próxima do neo-calcedonianismo do que do monotelismo posterior. Reconhece também que o anátema de 681 reflete o contexto político específico do concílio (necessidade de condenar TODOS os envolvidos na trajetória do erro, incluindo aqueles cuja responsabilidade era menor) e a lógica jurídica bizantina de responsabilidade objetiva pelos efeitos das próprias palavras, independentemente da intenção subjetiva. A distinção posterior entre 'heresia formal' e 'heresia material' — crucial na teologia católica — é uma categoria teológica ESCOLÁSTICA que os padres de 681 não empregavam. Portanto, a leitura mais rigorosa historicamente é: Honório foi imprudente, sua carta foi instrumentalizada por Sérgio, o concílio o condenou como cúmplice na cadeia de responsabilidade, Leão II confirmou a condenação nuançando-a, e a leitura católica posterior desenvolveu categorias interpretativas que preservam simultaneamente o anátema histórico e a doutrina da infalibilidade papal — leitura defensável, mas que não corresponde plenamente à autocompreensão dos padres de 681.",
  },
]