export const meta = {
  nome: 'São Filipe Néri',
  titulo: 'PRESBÍTERO · APÓSTOLO DE ROMA · FUNDADOR DO ORATÓRIO',
  subtitulo: '"State buoni, se potete." — "Sede bons, se puderdes."',
  categoria: 'presbiteros',
  slug: 'sao-filipe-neri',
  abas: [
    { slug: 'historia', label: 'História' },
    { slug: 'roma-do-seculo-xvi', label: 'Roma do século XVI' },
    { slug: 'formacao-e-sacerdocio', label: 'Formação e sacerdócio' },
    { slug: 'oratorio', label: 'Oratório' },
    { slug: 'apostolado', label: 'Apostolado' },
    { slug: 'pedagogia-espiritual', label: 'Pedagogia espiritual' },
    { slug: 'doutrina-espiritual', label: 'Doutrina espiritual' },
    { slug: 'carismas-e-milagres', label: 'Carismas e milagres' },
    { slug: 'relacoes-e-discipulos', label: 'Relações e discípulos' },
    { slug: 'reforma-catolica', label: 'Reforma Católica' },
    { slug: 'liturgia-e-musica', label: 'Liturgia e música' },
    { slug: 'culto-e-devocao', label: 'Culto e devoção' },
    { slug: 'beatificacao-e-canonizacao', label: 'Beatificação e canonização' },
    { slug: 'reliquias-e-lugares', label: 'Relíquias e lugares' },
    { slug: 'legado-e-influencia', label: 'Legado e influência' },
    { slug: 'fontes-e-historiografia', label: 'Fontes e historiografia' },
    { slug: 'iconografia', label: 'Iconografia' },
    { slug: 'frases', label: 'Frases' },
    { slug: 'obras', label: 'Obras e Escritos' },
  ],
};